/* Generated by re2c 3.1 on Wed May 13 23:59:57 2026 */
#line 1 "helpers/xguihtml.re"
/*
This file is part of "Avanor, the Land of Mystery" roguelike game
Home page: http://www.avanor.com/
Copyright (C) 2000-2003 Vadim Gaidukevich

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#include <stack>
#include <string>

#include "helpers/xgui.h"

#define	YYCTYPE		char
#define	YYCURSOR	cursor
#define	YYLIMIT		cursor
#define	YYMARKER	marker
#define	YYFILL(n)

#line 46 "helpers/xguihtml.re"


static int html_decode_color(char * text)
{
	int color = -1;
	YYCTYPE * cursor = text;
	YYCTYPE * marker = text;
color_open:;

#line 45 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
	switch (yych) {
		case '<': goto yy3;
		default: goto yy1;
	}
yy1:
	++YYCURSOR;
yy2:
#line 56 "helpers/xguihtml.re"
	{ return -1; }
#line 59 "helpers/xguihtml.cpp"
yy3:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'f': goto yy4;
		default: goto yy2;
	}
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy6;
		default: goto yy5;
	}
yy5:
	YYCURSOR = YYMARKER;
	goto yy2;
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy7;
		default: goto yy5;
	}
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy8;
		default: goto yy5;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy9;
		default: goto yy5;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy10;
		default: goto yy5;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy11;
		default: goto yy5;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy12;
		default: goto yy5;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy13;
		default: goto yy5;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy14;
		default: goto yy5;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy15;
		default: goto yy5;
	}
yy15:
	++YYCURSOR;
#line 55 "helpers/xguihtml.re"
	{ goto color_text; }
#line 133 "helpers/xguihtml.cpp"
}
#line 57 "helpers/xguihtml.re"

color_text:;

#line 139 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 12) YYFILL(12);
	yych = *YYCURSOR;
	switch (yych) {
		case 'a': goto yy19;
		case 'b': goto yy20;
		case 'c': goto yy21;
		case 'd': goto yy22;
		case 'f': goto yy23;
		case 'g': goto yy24;
		case 'l': goto yy25;
		case 'm': goto yy26;
		case 'n': goto yy27;
		case 'p': goto yy28;
		case 'r': goto yy29;
		case 's': goto yy30;
		case 't': goto yy31;
		case 'w': goto yy32;
		case 'y': goto yy33;
		default: goto yy17;
	}
yy17:
	++YYCURSOR;
yy18:
#line 76 "helpers/xguihtml.re"
	{ return -1; }
#line 167 "helpers/xguihtml.cpp"
yy19:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'q': goto yy34;
		default: goto yy18;
	}
yy20:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'l': goto yy36;
		case 'r': goto yy37;
		default: goto yy18;
	}
yy21:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'y': goto yy38;
		default: goto yy18;
	}
yy22:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'a': goto yy39;
		default: goto yy18;
	}
yy23:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'u': goto yy40;
		default: goto yy18;
	}
yy24:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'r': goto yy41;
		default: goto yy18;
	}
yy25:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'i': goto yy42;
		default: goto yy18;
	}
yy26:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'a': goto yy43;
		default: goto yy18;
	}
yy27:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'a': goto yy44;
		default: goto yy18;
	}
yy28:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'u': goto yy45;
		default: goto yy18;
	}
yy29:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'e': goto yy46;
		default: goto yy18;
	}
yy30:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'i': goto yy47;
		default: goto yy18;
	}
yy31:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'e': goto yy48;
		default: goto yy18;
	}
yy32:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'h': goto yy49;
		default: goto yy18;
	}
yy33:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'e': goto yy50;
		default: goto yy18;
	}
yy34:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy51;
		default: goto yy35;
	}
yy35:
	YYCURSOR = YYMARKER;
	goto yy18;
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy52;
		case 'u': goto yy53;
		default: goto yy35;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy54;
		default: goto yy35;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy55;
		default: goto yy35;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy56;
		default: goto yy35;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy57;
		default: goto yy35;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy58;
		case 'e': goto yy59;
		default: goto yy35;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy60;
		case 'm': goto yy61;
		default: goto yy35;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy62;
		case 'r': goto yy63;
		default: goto yy35;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'v': goto yy64;
		default: goto yy35;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy65;
		default: goto yy35;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy66;
		default: goto yy35;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy67;
		default: goto yy35;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy68;
		default: goto yy35;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy69;
		default: goto yy35;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy70;
		default: goto yy35;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy71;
		default: goto yy35;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'c': goto yy72;
		default: goto yy35;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy73;
		default: goto yy35;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'w': goto yy74;
		default: goto yy35;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy75;
		default: goto yy35;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'k': goto yy76;
		default: goto yy35;
	}
yy57:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy77;
		default: goto yy35;
	}
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy78;
		default: goto yy35;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy79;
		default: goto yy35;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy80;
		default: goto yy35;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy81;
		default: goto yy35;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy82;
		default: goto yy35;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy83;
		default: goto yy35;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy84;
		default: goto yy35;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'p': goto yy85;
		default: goto yy35;
	}
yy66:
	++YYCURSOR;
#line 64 "helpers/xguihtml.re"
	{ color = 4; goto color_close; }
#line 456 "helpers/xguihtml.cpp"
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'v': goto yy86;
		default: goto yy35;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy75;
		default: goto yy35;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy87;
		default: goto yy35;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy88;
		default: goto yy35;
	}
yy71:
	++YYCURSOR;
#line 71 "helpers/xguihtml.re"
	{ color = 11; goto color_close; }
#line 485 "helpers/xguihtml.cpp"
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'k': goto yy89;
		default: goto yy35;
	}
yy73:
	++YYCURSOR;
#line 69 "helpers/xguihtml.re"
	{ color = 9; goto color_close; }
#line 496 "helpers/xguihtml.cpp"
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy90;
		default: goto yy35;
	}
yy75:
	++YYCURSOR;
#line 63 "helpers/xguihtml.re"
	{ color = 3; goto color_close; }
#line 507 "helpers/xguihtml.cpp"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy91;
		default: goto yy35;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
		case 's': goto yy92;
		default: goto yy35;
	}
yy78:
	++YYCURSOR;
#line 68 "helpers/xguihtml.re"
	{ color = 8; goto color_close; }
#line 524 "helpers/xguihtml.cpp"
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy93;
		default: goto yy35;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy94;
		default: goto yy35;
	}
yy81:
	++YYCURSOR;
#line 70 "helpers/xguihtml.re"
	{ color = 10; goto color_close; }
#line 541 "helpers/xguihtml.cpp"
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy95;
		default: goto yy35;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy74;
		default: goto yy35;
	}
yy84:
	++YYCURSOR;
#line 61 "helpers/xguihtml.re"
	{ color = 1; goto color_close; }
#line 558 "helpers/xguihtml.cpp"
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy96;
		default: goto yy35;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy97;
		default: goto yy35;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy98;
		default: goto yy35;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy99;
		default: goto yy35;
	}
yy89:
	++YYCURSOR;
#line 60 "helpers/xguihtml.re"
	{ color = 0; goto color_close; }
#line 587 "helpers/xguihtml.cpp"
yy90:
	++YYCURSOR;
#line 66 "helpers/xguihtml.re"
	{ color = 6; goto color_close; }
#line 592 "helpers/xguihtml.cpp"
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy100;
		default: goto yy35;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'i': goto yy101;
		default: goto yy35;
	}
yy93:
	++YYCURSOR;
#line 62 "helpers/xguihtml.re"
	{ color = 2; goto color_close; }
#line 609 "helpers/xguihtml.cpp"
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'b': goto yy102;
		case 'c': goto yy103;
		case 'g': goto yy104;
		case 'm': goto yy105;
		case 'r': goto yy106;
		default: goto yy35;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy107;
		default: goto yy35;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy108;
		default: goto yy35;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy109;
		default: goto yy35;
	}
yy98:
	++YYCURSOR;
#line 75 "helpers/xguihtml.re"
	{ color = 15; goto color_close; }
#line 642 "helpers/xguihtml.cpp"
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'w': goto yy110;
		default: goto yy35;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy58;
		default: goto yy35;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy111;
		default: goto yy35;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy112;
		default: goto yy35;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy113;
		default: goto yy35;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy114;
		default: goto yy35;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy115;
		default: goto yy35;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy116;
		default: goto yy35;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy108;
		default: goto yy35;
	}
yy108:
	++YYCURSOR;
#line 65 "helpers/xguihtml.re"
	{ color = 5; goto color_close; }
#line 701 "helpers/xguihtml.cpp"
yy109:
	++YYCURSOR;
#line 67 "helpers/xguihtml.re"
	{ color = 7; goto color_close; }
#line 706 "helpers/xguihtml.cpp"
yy110:
	++YYCURSOR;
#line 74 "helpers/xguihtml.re"
	{ color = 14; goto color_close; }
#line 711 "helpers/xguihtml.cpp"
yy111:
	++YYCURSOR;
#line 73 "helpers/xguihtml.re"
	{ color = 13; goto color_close; }
#line 716 "helpers/xguihtml.cpp"
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'u': goto yy53;
		default: goto yy35;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy117;
		default: goto yy35;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy118;
		case 'e': goto yy119;
		default: goto yy35;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'g': goto yy120;
		default: goto yy35;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy121;
		default: goto yy35;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy71;
		default: goto yy35;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'y': goto yy109;
		default: goto yy35;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy122;
		default: goto yy35;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy123;
		default: goto yy35;
	}
yy121:
	++YYCURSOR;
#line 72 "helpers/xguihtml.re"
	{ color = 12; goto color_close; }
#line 776 "helpers/xguihtml.cpp"
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy81;
		default: goto yy35;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy124;
		default: goto yy35;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy101;
		default: goto yy35;
	}
}
#line 77 "helpers/xguihtml.re"

color_close:;

#line 800 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy126;
		case '>': goto yy129;
		default: goto yy128;
	}
yy126:
	++YYCURSOR;
yy127:
#line 81 "helpers/xguihtml.re"
	{ return -1; }
#line 815 "helpers/xguihtml.cpp"
yy128:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy127;
	goto yy131;
yy129:
	++YYCURSOR;
#line 80 "helpers/xguihtml.re"
	{ return color; }
#line 824 "helpers/xguihtml.cpp"
yy130:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy131:
	switch (yych) {
		case 0x00: goto yy132;
		case '>': goto yy129;
		default: goto yy130;
	}
yy132:
	YYCURSOR = YYMARKER;
	goto yy127;
}
#line 82 "helpers/xguihtml.re"

	return -1;
}

static std::string html_decode_ref(char * text)
{
	std::string ref;
	YYCTYPE * cursor = text;
	YYCTYPE * marker = text;
ref_open:;

#line 851 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	switch (yych) {
		case '<': goto yy136;
		default: goto yy134;
	}
yy134:
	++YYCURSOR;
yy135:
#line 94 "helpers/xguihtml.re"
	{ return ""; }
#line 865 "helpers/xguihtml.cpp"
yy136:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 'a': goto yy137;
		default: goto yy135;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy139;
		default: goto yy138;
	}
yy138:
	YYCURSOR = YYMARKER;
	goto yy135;
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'h': goto yy140;
		default: goto yy138;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy141;
		default: goto yy138;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy142;
		default: goto yy138;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'f': goto yy143;
		default: goto yy138;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy144;
		default: goto yy138;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
		case '"': goto yy145;
		default: goto yy138;
	}
yy145:
	++YYCURSOR;
#line 93 "helpers/xguihtml.re"
	{ goto ref_text; }
#line 921 "helpers/xguihtml.cpp"
}
#line 95 "helpers/xguihtml.re"

ref_text:;
	YYCTYPE * token = cursor;

#line 928 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy148;
		default: goto yy147;
	}
yy147:
	++YYCURSOR;
#line 100 "helpers/xguihtml.re"
	{ return ""; }
#line 1004 "helpers/xguihtml.cpp"
yy148:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy148;
		default: goto yy149;
	}
yy149:
#line 99 "helpers/xguihtml.re"
	{ ref = std::string(token, cursor - token); goto ref_close; }
#line 1079 "helpers/xguihtml.cpp"
}
#line 101 "helpers/xguihtml.re"

ref_close:;

#line 1085 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case '"': goto yy153;
		default: goto yy151;
	}
yy151:
	++YYCURSOR;
yy152:
#line 105 "helpers/xguihtml.re"
	{ return ""; }
#line 1099 "helpers/xguihtml.cpp"
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy154;
		default: goto yy152;
	}
yy154:
	++YYCURSOR;
#line 104 "helpers/xguihtml.re"
	{ return ref; }
#line 1110 "helpers/xguihtml.cpp"
}
#line 106 "helpers/xguihtml.re"

	return "";
}

#define NEXT_TOKEN() { goto next; }

void XGuiList::AddHtmlText(char * text)
{
	bool             is_ref = false;
	std::stack<char> colors;
	std::string      ref_name;
	std::string      out;

	YYCTYPE * cursor = text;
	YYCTYPE * marker = text;
next:
	YYCTYPE * token = cursor;

#line 1131 "helpers/xguihtml.cpp"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 8) YYFILL(8);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy156;
		case '\n':
		case '\r': goto yy159;
		case '<': goto yy161;
		default: goto yy157;
	}
yy156:
	++YYCURSOR;
#line 219 "helpers/xguihtml.re"
	{
		if (!out.empty())
		{
			AddItem(new XGuiItem_Text(out.c_str(), is_ref));
			out = "";
		}
		return;
	}
#line 1155 "helpers/xguihtml.cpp"
yy157:
	++YYCURSOR;
yy158:
#line 208 "helpers/xguihtml.re"
	{
		if (out.empty() && !colors.empty())
		{
			out += (char)0x1F;
			out += (char)colors.top();
		}
		out += *token;
		NEXT_TOKEN();
	}
#line 1169 "helpers/xguihtml.cpp"
yy159:
	++YYCURSOR;
yy160:
#line 125 "helpers/xguihtml.re"
	{
		NEXT_TOKEN();
	}
#line 1177 "helpers/xguihtml.cpp"
yy161:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
		case 0x00: goto yy158;
		case '!': goto yy165;
		case '/': goto yy166;
		case 'a': goto yy169;
		case 'b': goto yy170;
		case 'f': goto yy171;
		case 'h': goto yy172;
		case 't': goto yy173;
		default: goto yy163;
	}
yy162:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy163:
	switch (yych) {
		case 0x00: goto yy164;
		case '>': goto yy167;
		default: goto yy162;
	}
yy164:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
		case 0: goto yy158;
		case 1: goto yy168;
		default: goto yy160;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy174;
		default: goto yy163;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy175;
		case 'f': goto yy176;
		case 'h': goto yy177;
		default: goto yy163;
	}
yy167:
	++YYCURSOR;
yy168:
#line 203 "helpers/xguihtml.re"
	{
		NEXT_TOKEN();
	}
#line 1230 "helpers/xguihtml.cpp"
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy178;
		default: goto yy163;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'r': goto yy179;
		default: goto yy163;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy180;
		default: goto yy163;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy181;
		default: goto yy163;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy182;
		default: goto yy163;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy183;
		default: goto yy163;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy184;
		default: goto yy163;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'o': goto yy185;
		default: goto yy163;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6': goto yy186;
		default: goto yy163;
	}
yy178:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '>': goto yy187;
		default: goto yy178;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy188;
		default: goto yy163;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy189;
		case 'r': goto yy190;
		default: goto yy163;
	}
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'a': goto yy191;
		default: goto yy163;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'b': goto yy192;
		default: goto yy163;
	}
yy183:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '-': goto yy193;
		case '>': goto yy194;
		default: goto yy183;
	}
yy184:
	++YYCURSOR;
#line 179 "helpers/xguihtml.re"
	{
		if (!out.empty())
		{
			AddItem(new XGuiItem_Text(out.c_str(), is_ref));
			out = "";
		}
		is_ref = false;
		ref_name = "";
		NEXT_TOKEN();
	}
#line 1347 "helpers/xguihtml.cpp"
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'n': goto yy195;
		default: goto yy163;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy196;
		default: goto yy163;
	}
yy187:
	++YYCURSOR;
#line 160 "helpers/xguihtml.re"
	{
		ref_name = html_decode_ref(token);
		if (!ref_name.empty())
		{
			if (!out.empty())
			{
				AddItem(new XGuiItem_Text(out.c_str(), is_ref));
				out = "";
			}
			is_ref = true;
		}
		else
		{
			out += std::string(token, cursor - token);
		}
		NEXT_TOKEN();
	}
#line 1380 "helpers/xguihtml.cpp"
yy188:
	++YYCURSOR;
#line 191 "helpers/xguihtml.re"
	{
		out += '\n';
		NEXT_TOKEN();
	}
#line 1388 "helpers/xguihtml.cpp"
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy197;
		default: goto yy163;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'm': goto yy198;
		default: goto yy163;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'd': goto yy199;
		default: goto yy163;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'l': goto yy200;
		default: goto yy163;
	}
yy193:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '-': goto yy201;
		case '>': goto yy194;
		default: goto yy183;
	}
yy194:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy168;
	goto yy203;
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
		case 't': goto yy205;
		default: goto yy163;
	}
yy196:
	++YYCURSOR;
#line 197 "helpers/xguihtml.re"
	{
		out += "\n\n";
		NEXT_TOKEN();
	}
#line 1441 "helpers/xguihtml.cpp"
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
		case ' ': goto yy206;
		default: goto yy163;
	}
yy198:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy207;
		default: goto yy163;
	}
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy208;
		default: goto yy163;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
		case 'e': goto yy209;
		default: goto yy163;
	}
yy201:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '-': goto yy201;
		case '>': goto yy210;
		default: goto yy183;
	}
yy202:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy203:
	switch (yych) {
		case 0x00: goto yy164;
		case '-': goto yy204;
		default: goto yy202;
	}
yy204:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '-': goto yy211;
		default: goto yy202;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy212;
		default: goto yy163;
	}
yy206:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '>': goto yy213;
		default: goto yy206;
	}
yy207:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy168;
	goto yy215;
yy208:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy168;
	goto yy218;
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
		case '>': goto yy220;
		default: goto yy163;
	}
yy210:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy160;
		case '-': goto yy204;
		default: goto yy202;
	}
yy211:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '-': goto yy211;
		case '>': goto yy210;
		default: goto yy202;
	}
yy212:
	++YYCURSOR;
#line 146 "helpers/xguihtml.re"
	{
		if (!colors.empty())
		{
			colors.pop();
			out += (char)0x1F;
			if (!colors.empty())
				out += (char)colors.top();
			else
				out += 7; // lightgray
		}
		NEXT_TOKEN();
	}
#line 1561 "helpers/xguihtml.cpp"
yy213:
	++YYCURSOR;
#line 130 "helpers/xguihtml.re"
	{
		int color = html_decode_color(token);
		if (color != -1)
		{
			colors.push(color);
			out += (char)0x1F;
			out += (char)color;
		}
		else
		{
			out += std::string(token, cursor - token);
		}
		NEXT_TOKEN();
	}
#line 1579 "helpers/xguihtml.cpp"
yy214:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy215:
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy216;
		default: goto yy214;
	}
yy216:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '/': goto yy221;
		case '<': goto yy216;
		default: goto yy214;
	}
yy217:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy218:
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy219;
		default: goto yy217;
	}
yy219:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '/': goto yy222;
		case '<': goto yy219;
		default: goto yy217;
	}
yy220:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x00) goto yy168;
	goto yy224;
yy221:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy216;
		case 'f': goto yy226;
		default: goto yy214;
	}
yy222:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy219;
		case 'h': goto yy227;
		default: goto yy217;
	}
yy223:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy224:
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		default: goto yy223;
	}
yy225:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '/': goto yy228;
		case '<': goto yy225;
		default: goto yy223;
	}
yy226:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy216;
		case 'o': goto yy229;
		default: goto yy214;
	}
yy227:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy219;
		case 'e': goto yy230;
		default: goto yy217;
	}
yy228:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		case 't': goto yy231;
		default: goto yy223;
	}
yy229:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy216;
		case 'r': goto yy232;
		default: goto yy214;
	}
yy230:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy219;
		case 'a': goto yy233;
		default: goto yy217;
	}
yy231:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		case 'a': goto yy234;
		default: goto yy223;
	}
yy232:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy216;
		case 'm': goto yy235;
		default: goto yy214;
	}
yy233:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy219;
		case 'd': goto yy236;
		default: goto yy217;
	}
yy234:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		case 'b': goto yy237;
		default: goto yy223;
	}
yy235:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy216;
		case '>': goto yy238;
		default: goto yy214;
	}
yy236:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy219;
		case '>': goto yy239;
		default: goto yy217;
	}
yy237:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		case 'l': goto yy240;
		default: goto yy223;
	}
yy238:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy160;
		case '<': goto yy216;
		default: goto yy214;
	}
yy239:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy160;
		case '<': goto yy219;
		default: goto yy217;
	}
yy240:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		case 'e': goto yy241;
		default: goto yy223;
	}
yy241:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy164;
		case '<': goto yy225;
		case '>': goto yy242;
		default: goto yy223;
	}
yy242:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00: goto yy160;
		case '<': goto yy225;
		default: goto yy223;
	}
}
#line 227 "helpers/xguihtml.re"

}
