mkdir c:\gout\creature
copy c:\xwork\creature\*.* c:\gout\creature\*.*

mkdir c:\gout\engine
copy c:\xwork\engine\*.* c:\gout\engine\*.*

mkdir c:\gout\item
copy c:\xwork\item\*.* c:\gout\item\*.*

mkdir c:\gout\helpers
copy c:\xwork\helpers\*.* c:\gout\helpers\*.*

mkdir c:\gout\global
copy c:\xwork\global\*.* c:\gout\global\*.*

mkdir c:\gout\game
copy c:\xwork\game\*.* c:\gout\game\*.*

mkdir c:\gout\magic
copy c:\xwork\magic\*.* c:\gout\magic\*.*

mkdir c:\gout\map
copy c:\xwork\map\*.* c:\gout\map\*.*

mkdir c:\gout\other
copy c:\xwork\other\*.* c:\gout\other\*.*

mkdir c:\gout\manual
copy c:\xwork\manual\*.* c:\gout\manual\*.*

copy c:\xwork\*.h c:\gout\*.h
copy c:\xwork\*.cpp c:\gout\*.cpp
copy c:\xwork\*.dsw c:\gout\*.dsw
copy c:\xwork\*.dsp c:\gout\*.dsp
copy c:\xwork\*.txt c:\gout\*.txt
copy c:\xwork\make*.* c:\gout\*.*
