# This file is automatically generated by RHIDE Version 1.4.7.8
# created from within RHIDE
vpath_src=creature engine game global helpers item magic map other
vpath %.c $(vpath_src)
vpath %.cc $(vpath_src)
vpath %.cpp $(vpath_src)
vpath %.C $(vpath_src)
vpath %.cxx $(vpath_src)
vpath %.s $(vpath_src)
vpath %.S $(vpath_src)
vpath %.p $(vpath_src)
vpath %.pas $(vpath_src)
vpath %.f $(vpath_src)
vpath %.for $(vpath_src)
vpath %.F $(vpath_src)
vpath %.fpp $(vpath_src)
vpath %.i $(vpath_src)
vpath %.ii $(vpath_src)
vpath %.m $(vpath_src)
vpath %.asm $(vpath_src)
vpath %.nsm $(vpath_src)
vpath_obj=./debug/
vpath %.o $(vpath_obj)
RHIDE_GCC=gcc
RHIDE_AS=gcc
RHIDE_GXX=gcc
RHIDE_GPC=gpc
RHIDE_FPC=ppc386
RHIDE_AR=ar
RHIDE_LD=gcc
RHIDE_G77=g77
RHIDE_NASM=nasm
RHIDE_LD_PASCAL=gpc
RHIDE_LD_FPC=ld
RHIDE_GNATBIND=gnatbind
RHIDE_RM=rm
RHIDE_ARFLAGS=rcs
RHIDE_TYPED_LIBS.f=g2c m
RHIDE_TYPED_LIBS.for=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.F=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS.fpp=$(RHIDE_TYPED_LIBS.f)
RHIDE_TYPED_LIBS_GPC=gpc m
RHIDE_TYPED_LIBS_FPC=fpc
RHIDE_TYPED_LIBS.p=$(RHIDE_TYPED_LIBS_$(PASCAL_TYPE))
RHIDE_TYPED_LIBS.pas=$(RHIDE_TYPED_LIBS.p)
RHIDE_TYPED_LIBS.pp=$(RHIDE_TYPED_LIBS_FPC)
RHIDE_TYPED_LIBS_DJGPP.cc=stdcxx
RHIDE_TYPED_LIBS_Linux.cc=stdc++
RHIDE_TYPED_LIBS.cc=$(RHIDE_TYPED_LIBS_$(RHIDE_OS).cc)
RHIDE_TYPED_LIBS.cpp=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.cxx=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.C=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.ii=$(RHIDE_TYPED_LIBS.cc)
RHIDE_TYPED_LIBS.l=fl
RHIDE_TYPED_LIBS.m=objc
RHIDE_TYPED_LIBS.adb=gnat
RHIDE_TYPED_LIBS_SUFFIXES=$(sort $(foreach item,$(PROJECT_ITEMS),$(suffix\
	$(item))))
RHIDE_TYPED_LIBS=$(foreach\
	suff,$(RHIDE_TYPED_LIBS_SUFFIXES),$(RHIDE_TYPED_LIBS$(suff)))
RHIDE_INCLUDES=$(SPECIAL_CFLAGS) $(addprefix -I,$(INCLUDE_DIRS))
RHIDE_LIBDIRS=$(addprefix -L,$(LIB_DIRS))
RHIDE_LIBS=$(addprefix -l,$(LIBS) $(RHIDE_TYPED_LIBS) $(RHIDE_OS_LIBS))
RHIDE_LDFLAGS=$(SPECIAL_LDFLAGS) $(addprefix -Xlinker ,$(LD_EXTRA_FLAGS))
RHIDE_NASM_TARGET_DJGPP=coff
RHIDE_NASM_TARGET_Linux=elf
RHIDE_NASM_TARGET=$(RHIDE_NASM_TARGET_$(RHIDE_OS))
RHIDE_COMPILE_NASM=$(RHIDE_NASM) -f $(RHIDE_NASM_TARGET) $(LOCAL_OPT) -o\
	$(OUTFILE)  $(SOURCE_NAME)
RHIDE_COMPILE_FORTRAN=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_FORTRAN_FORCE=$(RHIDE_G77) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_F_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x f77 $(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_C=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  $(CPPFLAGS) $(CFLAGS) $(RHIDE_OS_CFLAGS) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_C_FORCE=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	-x c $(LOCAL_OPT)  $(CPPFLAGS) $(CFLAGS) $(RHIDE_OS_CFLAGS) -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_CC=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(CPPFLAGS) $(CXXFLAGS)\
	$(RHIDE_OS_CXXFLAGS) $(LOCAL_OPT)   -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_CC_FORCE=$(RHIDE_GXX) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS)\
	$(C_CXX_LANG_FLAGS) $(C_EXTRA_FLAGS)  $(CPPFLAGS) $(CXXFLAGS)\
	$(RHIDE_OS_CXXFLAGS) -x c++ $(LOCAL_OPT)   -c $(SOURCE_NAME) -o\
	$(OUTFILE)
RHIDE_COMPILE_ASM=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_ASM_FORCE=$(RHIDE_AS) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_EXTRA_FLAGS) -x assembler\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_GPC_FLAGS=$(RHIDE_INCLUDES) $(C_DEBUG_FLAGS) $(C_OPT_FLAGS)\
	$(C_WARN_FLAGS)  $(C_P_LANG_FLAGS) $(C_EXTRA_FLAGS)
RHIDE_COMPILE_GPC=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) $(LOCAL_OPT)  -c\
	$(SOURCE_NAME) -o $(OUTFILE)
RHIDE_COMPILE_GPC_FORCE=$(RHIDE_GPC) $(RHIDE_GPC_FLAGS) -x pascal\
	$(LOCAL_OPT)  -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_FPC_FLAGS=$(C_FPC_LANG_FLAGS) $(LOCAL_OPT) $(addprefix\
	-Up,$(INCLUDE_DIRS))  $(C_EXTRA_FLAGS)
RHIDE_COMPILE_FPC=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -E- $(SOURCE_NAME)
RHIDE_COMPILE_FPC_FORCE=$(RHIDE_FPC) $(RHIDE_FPC_FLAGS) -B -E-\
	$(SOURCE_NAME)
RHIDE_COMPILE_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(LDFLAGS) $(RHIDE_LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_GPC=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS)\
	-o $(OUTFILE)  $(OBJFILES) $(LIBRARIES) $(RHIDE_LDFLAGS) $(LDFLAGS)\
	$(RHIDE_LIBS)
RHIDE_COMPILE_LINK_GPC_AUTOMAKE=$(RHIDE_LD_PASCAL) $(RHIDE_LIBDIRS)  -o\
	$(OUTFILE) --automake="$(strip $(RHIDE_GPC_FLAGS))"\
	$(RHIDE_GPC_FLAGS)  $(SOURCE_NAME) $(LIBRARIES) $(LDFLAGS)\
	$(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE_PASCAL=$(RHIDE_COMPILE_$(PASCAL_TYPE))
RHIDE_COMPILE_PASCAL_FORCE=$(RHIDE_COMPILE_$(PASCAL_TYPE)_FORCE)
RHIDE_COMPILE_LINK_PASCAL_AUTOMAKE=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE)_AUTOMAKE)
RHIDE_COMPILE_LINK_PASCAL=$(RHIDE_COMPILE_LINK_$(PASCAL_TYPE))
RHIDE_FPC_LIBDIRS_DJGPP=$(DJDIR)/lib
RHIDE_FPC_LIBDIRS_Linux=/usr/local/lib /usr/lib /lib
RHIDE_FPC_LIBDIRS=$(RHIDE_FPC_LIBDIRS_$(RHIDE_OS))
RHIDE_FPC_LINK_FLAGS_DJGPP=-O coff-go32-exe $(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS_Linux=$(RHIDE_LIBDIRS) $(addprefix\
	-L,$(RHIDE_FPC_LIBDIRS))
RHIDE_FPC_LINK_FLAGS=$(RHIDE_FPC_LINK_FLAGS_$(RHIDE_OS))
RHIDE_COMPILE_LINK_FPC=$(RHIDE_LD_FPC) -o $(OUTFILE) $(OBJFILES)\
	$(RHIDE_FPC_LINK_FLAGS)   $(LIBRARIES) $(RHIDE_LIBS)
RHIDE_COMPILE_LINK_FPC_AUTOMAKE=$(RHIDE_FPC) -o$(OUTFILE) $(SOURCE_NAME)\
	$(RHIDE_FPC_FLAGS) -E+
RHIDE_COMPILE_ARCHIVE=$(RHIDE_AR) $(RHIDE_ARFLAGS) $(OUTFILE) $(OBJFILES)
RHIDE_COMPILE_ADA=$(RHIDE_GCC) $(RHIDE_INCLUDES) $(C_DEBUG_FLAGS)\
	$(C_OPT_FLAGS)  $(C_WARN_FLAGS) $(C_C_LANG_FLAGS) $(C_EXTRA_FLAGS)\
	$(LOCAL_OPT)  $(C_ADA_LANG_FLAGS)  $(CPPFLAGS) $(CFLAGS)\
	$(RHIDE_OS_CFLAGS) -c $(SOURCE_NAME) -o $(OUTFILE)
RHIDE_ADA_BIND_FILE=$(addprefix _,$(setsuffix .c,$(OUTFILE)))
RHIDE_COMPILE_LINK_ADA_BIND=$(RHIDE_GNATBIND) -o $(RHIDE_ADA_BIND_FILE)\
	$(setsuffix .ali,$(OUTFILE))
RHIDE_COMPILE_LINK_ADA_LINK=$(RHIDE_LD) $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(RHIDE_ADA_BIND_FILE) $(OBJFILES) $(LIBRARIES)\
	$(LDFLAGS)  $(RHIDE_LDFLAGS) $(RHIDE_LIBS)
_RHIDE_COMPILE_LINK_ADA=$(RHIDE_COMPILE_LINK_ADA_BIND);\
	$(RHIDE_COMPILE_LINK_ADA_LINK);   $(RHIDE_RM)\
	$(RHIDE_ADA_BIND_FILE)
RHIDE_COMPILE_LINK_ADA=gnatbl $(RHIDE_LIBDIRS) $(C_EXTRA_FLAGS) -o\
	$(OUTFILE)  $(setsuffix .ali,$(OUTFILE)) $(LIBRARIES) $(LDFLAGS) \
	$(RHIDE_LDFLAGS) $(RHIDE_LIBS)
RHIDE_COMPILE.c.o=$(RHIDE_COMPILE_C)
RHIDE_COMPILE.cc.o=$(RHIDE_COMPILE_CC)
RHIDE_COMPILE.p.o=$(RHIDE_COMPILE_PASCAL)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.pp.o=$(RHIDE_COMPILE_FPC)
RHIDE_COMPILE.pas.s.GPC=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_GPC))
RHIDE_COMPILE.pas.s.FPC=$(RHIDE_COMPILE_FPC) -a -s
RHIDE_COMPILE.pas.s=$(RHIDE_COMPILE.pas.s.$(PASCAL_TYPE))
RHIDE_COMPILE.f.o=$(RHIDE_COMPILE_FORTRAN)
RHIDE_COMPILE.nsm.o=$(RHIDE_COMPILE_NASM)
RHIDE_COMPILE.s.o=$(RHIDE_COMPILE_ASM)
RHIDE_COMPILE.c.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.c.i=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_C))
RHIDE_COMPILE.i.s=$(RHIDE_COMPILE.c.s)
RHIDE_COMPILE.cc.s=$(subst -c $(SOURCE_NAME),-S\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.cc.ii=$(subst -c $(SOURCE_NAME),-E\
	$(SOURCE_NAME),$(RHIDE_COMPILE_CC))
RHIDE_COMPILE.ii.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cpp.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.cxx.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.C.o=$(RHIDE_COMPILE.cc.o)
RHIDE_COMPILE.pas.o=$(RHIDE_COMPILE.p.o)
RHIDE_COMPILE.for.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.F.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.fpp.o=$(RHIDE_COMPILE.f.o)
RHIDE_COMPILE.asm.o=$(RHIDE_COMPILE.nsm.o)
RHIDE_COMPILE.cpp.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cxx.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.C.s=$(RHIDE_COMPILE.cc.s)
RHIDE_COMPILE.cpp.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.cxx.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.C.ii=$(RHIDE_COMPILE.cc.ii)
RHIDE_COMPILE.adb.o=$(RHIDE_COMPILE_ADA)
RHIDE_FSDB=fsdb $(OUTFILE) $(addprefix -p ,$(SRC_DIRS)) $(PROG_ARGS)
RHIDE_GDB=gdb $(OUTFILE) $(addprefix -d ,$(SRC_DIRS))
DEFAULT_GREP_MASK=*.[cfhmnps]*
RHIDE_GREP=grep -n $(prompt arguments for GREP,$(WUC) $(DEFAULT_GREP_MASK))
RHIDE_GPROF=gprof $(OUTFILE)
RHIDE_RLOG=$(shell rlog -R $(rlog_arg))
RHIDE_CO=$(shell co -q $(co_arg))
RHIDE_STANDARD_INCLUDES_DJGPP=$(addprefix $(DJDIR)/,include include/sys\
	lang/cxx lang/cxx/std)
RHIDE_STANDARD_INCLUDES_Linux=$(addprefix /usr/,include include/sys\
	include/g++ include/g++/std)
RHIDE_STANDARD_INCLUDES=$(RHIDE_STANDARD_INCLUDES_$(RHIDE_OS))
RHIDE_CONFIG_DIRS_DJGPP=. $(RHIDE_SHARE) $(HOME) $(DJDIR)/share/rhide
RHIDE_CONFIG_DIRS_Linux=. $(RHIDE_SHARE) $(HOME) /usr/local/share/rhide\
	/usr/share/rhide  /local/share/rhide /share/rhide
RHIDE_CONFIG_DIRS=$(RHIDE_CONFIG_DIRS_$(RHIDE_OS))\
	$(RHIDE_BIN_DIR)/../share/rhide
RHIDE_PATH_SEPARATOR_DJGPP=;
RHIDE_PATH_SEPARATOR_Linux=:
RHIDE_PATH_SEPARATOR=$(RHIDE_PATH_SEPARATOR_$(RHIDE_OS))
RHIDE_TYPED_LIBS_DJGPP.cc=stdcxx
RHIDE_TYPED_LIBS_DJGPP.cxx=stdcxx
RHIDE_TYPED_LIBS_DJGPP.cpp=stdcxx
RHIDE_TYPED_LIBS_DJGPP.f=g2c m
INCLUDE_DIRS=./engine/ ./item/ ./game/ ./global/ ./magic/ ./helpers/ ./map/\
	./creature/ ./ ./other/
LIB_DIRS=
C_DEBUG_FLAGS=-g
C_OPT_FLAGS=-O3
C_WARN_FLAGS=
C_C_LANG_FLAGS=
C_CXX_LANG_FLAGS=
C_P_LANG_FLAGS=
C_FPC_LANG_FLAGS=
C_F_LANG_FLAGS=
C_ADA_LANG_FLAGS=
LIBS=
LD_EXTRA_FLAGS=
C_EXTRA_FLAGS=-D NDEBUG
LOCAL_OPT=$(subst ___~~~___, ,$(subst $(notdir $<)___,,$(filter $(notdir\
	$<)___%,$(LOCAL_OPTIONS))))
OBJFILES=debug/ai_view.o debug/anycr.o debug/bandit.o debug/bodypart.o\
	debug/cats.o debug/cave.o debug/cbuilder.o debug/creature.o\
	debug/creature2.o debug/crf.o debug/dearfcave.o debug/deity.o\
	debug/dice.o debug/dogs.o debug/dwarfcity.o debug/farmer.o\
	debug/game.o debug/global.o debug/goblins.o debug/hiscore.o\
	debug/humans.o debug/insects.o debug/item.o debug/item_misc.o\
	debug/itemdb.o debug/itemf.o debug/kobolds.o\
	debug/lbuilderpalette.o debug/ldebug.o debug/location.o debug/los.o\
	debug/magic.o debug/main.o debug/mainloc.o debug/manual.o\
	debug/map.o debug/modifer.o debug/modifers.o debug/msgwin.o\
	debug/mushcave.o debug/orcs.o debug/other_misc.o debug/people.o\
	debug/quest.o debug/rat_cell.o debug/rats.o debug/rect.o\
	debug/resist.o debug/royal_guard.o debug/setting.o debug/shop.o\
	debug/shopkeeper.o debug/skeep_ai.o debug/skill.o debug/skills.o\
	debug/snakes.o debug/special.o debug/spell.o debug/spellfactory.o\
	debug/stats.o debug/std_ai.o debug/strproc.o debug/udeadtomb.o\
	debug/undeads.o debug/uniquei.o debug/uniquem.o\
	debug/wizard_dungeon.o debug/wmagic.o debug/wskills.o\
	debug/xamulet.o debug/xanyfood.o debug/xanyplace.o debug/xapi.o\
	debug/xarchive.o debug/xarmor.o debug/xbaseobj.o\
	debug/xbasicspells.o debug/xbook.o debug/xboots.o debug/xcap.o\
	debug/xcloak.o debug/xclothe.o debug/xcorpse.o debug/xenhance.o\
	debug/xgen.o debug/xgloves.o debug/xgui.o debug/xherb.o\
	debug/xhero.o debug/xhero2.o debug/xhero3.o debug/xmapobj.o\
	debug/xmissile.o debug/xmissileweapon.o debug/xmoney.o\
	debug/xobject.o debug/xpotion.o debug/xration.o debug/xring.o\
	debug/xscroll.o debug/xshedule.o debug/xshield.o debug/xstring.o\
	debug/xtime.o debug/xtool.o debug/xweapon.o
LIBRARIES=
SOURCE_NAME=$<
OUTFILE=$@
SPECIAL_CFLAGS=
SPECIAL_LDFLAGS=-pg
PROG_ARGS=
SRC_DIRS=creature engine game global helpers item magic map other
WUC=
EDITORS=
RHIDE_OS=$(RHIDE_OS_)
ifeq ($(strip $(RHIDE_OS)),)
ifneq ($(strip $(DJDIR)),)
RHIDE_OS_:=DJGPP
else
RHIDE_OS_:=$(shell uname)
endif
endif

MAIN_TARGET=avanor.exe
PROJECT_ITEMS=ai_view.cpp anycr.cpp bandit.cpp bodypart.cpp cats.cpp\
	cave.cpp cbuilder.cpp creature.cpp creature2.cpp crf.cpp\
	dearfcave.cpp deity.cpp dice.cpp dogs.cpp dwarfcity.cpp farmer.cpp\
	game.cpp global.cpp goblins.cpp hiscore.cpp humans.cpp insects.cpp\
	item.cpp item_misc.cpp itemdb.cpp itemf.cpp kobolds.cpp\
	lbuilderpalette.cpp ldebug.cpp location.cpp los.cpp magic.cpp\
	main.cpp mainloc.cpp manual.cpp map.cpp modifer.cpp modifers.cpp\
	msgwin.cpp mushcave.cpp orcs.cpp other_misc.cpp people.cpp\
	quest.cpp rat_cell.cpp rats.cpp rect.cpp resist.cpp royal_guard.cpp\
	setting.cpp shop.cpp shopkeeper.cpp skeep_ai.cpp skill.cpp\
	skills.cpp snakes.cpp special.cpp spell.cpp spellfactory.cpp\
	stats.cpp std_ai.cpp strproc.cpp udeadtomb.cpp undeads.cpp\
	uniquei.cpp uniquem.cpp wizard_dungeon.cpp wmagic.cpp wskills.cpp\
	xamulet.cpp xanyfood.cpp xanyplace.cpp xapi.cpp xarchive.cpp\
	xarmor.cpp xbaseobj.cpp xbasicspells.cpp xbook.cpp xboots.cpp\
	xcap.cpp xcloak.cpp xclothe.cpp xcorpse.cpp xenhance.cpp xgen.cpp\
	xgloves.cpp xgui.cpp xherb.cpp xhero.cpp xhero2.cpp xhero3.cpp\
	xmapobj.cpp xmissile.cpp xmissileweapon.cpp xmoney.cpp xobject.cpp\
	xpotion.cpp xration.cpp xring.cpp xscroll.cpp xshedule.cpp\
	xshield.cpp xstring.cpp xtime.cpp xtool.cpp xweapon.cpp
DEFAULT_MASK=*.cpp
RHIDE_BIN_DIR=c:/djgpp/bin
PASCAL_TYPE=GPC
%.o: %.c
	$(RHIDE_COMPILE.c.o)
%.o: %.i
	$(RHIDE_COMPILE_C)
%.o: %.cc
	$(RHIDE_COMPILE.cc.o)
%.o: %.cpp
	$(RHIDE_COMPILE.cpp.o)
%.o: %.cxx
	$(RHIDE_COMPILE.cxx.o)
%.o: %.C
	$(RHIDE_COMPILE.C.o)
%.o: %.ii
	$(RHIDE_COMPILE_CC)
%.o: %.s
	$(RHIDE_COMPILE.s.o)
%.o: %.S
	$(RHIDE_COMPILE_ASM)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.s: %.i
	$(RHIDE_COMPILE.i.s)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
%.o: %.pas
	$(RHIDE_COMPILE.pas.o)
%.o: %.p
	$(RHIDE_COMPILE.p.o)
%.o: %.pp
	$(RHIDE_COMPILE.pp.o)
%.s: %.pas
	$(RHIDE_COMPILE.pas.s)
%.o: %.m
	$(RHIDE_COMPILE_OBJC)
%.o: %.f
	$(RHIDE_COMPILE.f.o)
%.o: %.for
	$(RHIDE_COMPILE.for.o)
%.o: %.F
	$(RHIDE_COMPILE.F.o)
%.o: %.fpp
	$(RHIDE_COMPILE.fpp.o)
%.o: %.asm
	$(RHIDE_COMPILE.asm.o)
%.o: %.nsm
	$(RHIDE_COMPILE.nsm.o)
%.o: %.adb
	$(RHIDE_COMPILE.adb.o)
%.i: %.c
	$(RHIDE_COMPILE.c.i)
%.s: %.c
	$(RHIDE_COMPILE.c.s)
%.ii: %.cc
	$(RHIDE_COMPILE.cc.ii)
%.s: %.cc
	$(RHIDE_COMPILE.cc.s)
%.ii: %.cpp
	$(RHIDE_COMPILE.cpp.ii)
%.s: %.cpp
	$(RHIDE_COMPILE.cpp.s)
%.ii: %.cxx
	$(RHIDE_COMPILE.cxx.ii)
%.s: %.cxx
	$(RHIDE_COMPILE.cxx.s)
%.ii: %.C
	$(RHIDE_COMPILE.C.ii)
%.s: %.C
	$(RHIDE_COMPILE.C.s)
all::
DEPS_0= debug/ai_view.o debug/anycr.o debug/bandit.o debug/bodypart.o\
	debug/cats.o debug/cave.o debug/cbuilder.o debug/creature.o\
	debug/creature2.o debug/crf.o debug/dearfcave.o debug/deity.o\
	debug/dice.o debug/dogs.o debug/dwarfcity.o debug/farmer.o\
	debug/game.o debug/global.o debug/goblins.o debug/hiscore.o\
	debug/humans.o debug/insects.o debug/item.o debug/item_misc.o\
	debug/itemdb.o debug/itemf.o debug/kobolds.o\
	debug/lbuilderpalette.o debug/ldebug.o debug/location.o debug/los.o\
	debug/magic.o debug/main.o debug/mainloc.o debug/manual.o\
	debug/map.o debug/modifer.o debug/modifers.o debug/msgwin.o\
	debug/mushcave.o debug/orcs.o debug/other_misc.o debug/people.o\
	debug/quest.o debug/rat_cell.o debug/rats.o debug/rect.o\
	debug/resist.o debug/royal_guard.o debug/setting.o debug/shop.o\
	debug/shopkeeper.o debug/skeep_ai.o debug/skill.o debug/skills.o\
	debug/snakes.o debug/special.o debug/spell.o debug/spellfactory.o\
	debug/stats.o debug/std_ai.o debug/strproc.o debug/udeadtomb.o\
	debug/undeads.o debug/uniquei.o debug/uniquem.o\
	debug/wizard_dungeon.o debug/wmagic.o debug/wskills.o\
	debug/xamulet.o debug/xanyfood.o debug/xanyplace.o debug/xapi.o\
	debug/xarchive.o debug/xarmor.o debug/xbaseobj.o\
	debug/xbasicspells.o debug/xbook.o debug/xboots.o debug/xcap.o\
	debug/xcloak.o debug/xclothe.o debug/xcorpse.o debug/xenhance.o\
	debug/xgen.o debug/xgloves.o debug/xgui.o debug/xherb.o\
	debug/xhero.o debug/xhero2.o debug/xhero3.o debug/xmapobj.o\
	debug/xmissile.o debug/xmissileweapon.o debug/xmoney.o\
	debug/xobject.o debug/xpotion.o debug/xration.o debug/xring.o\
	debug/xscroll.o debug/xshedule.o debug/xshield.o debug/xstring.o\
	debug/xtime.o debug/xtool.o debug/xweapon.o 
NO_LINK=
LINK_FILES=$(filter-out $(NO_LINK),$(DEPS_0))
avanor.exe:: $(DEPS_0)
	$(RHIDE_COMPILE_LINK)
DEPS_1=ai_view.cpp
debug/ai_view.o:: $(DEPS_1)
	$(RHIDE_COMPILE.cpp.o)
DEPS_2=anycr.cpp
debug/anycr.o:: $(DEPS_2)
	$(RHIDE_COMPILE.cpp.o)
DEPS_3=bandit.cpp
debug/bandit.o:: $(DEPS_3)
	$(RHIDE_COMPILE.cpp.o)
DEPS_4=bodypart.cpp
debug/bodypart.o:: $(DEPS_4)
	$(RHIDE_COMPILE.cpp.o)
DEPS_5=cats.cpp
debug/cats.o:: $(DEPS_5)
	$(RHIDE_COMPILE.cpp.o)
DEPS_6=cave.cpp
debug/cave.o:: $(DEPS_6)
	$(RHIDE_COMPILE.cpp.o)
DEPS_7=cbuilder.cpp
debug/cbuilder.o:: $(DEPS_7)
	$(RHIDE_COMPILE.cpp.o)
DEPS_8=creature.cpp
debug/creature.o:: $(DEPS_8)
	$(RHIDE_COMPILE.cpp.o)
DEPS_9=creature2.cpp
debug/creature2.o:: $(DEPS_9)
	$(RHIDE_COMPILE.cpp.o)
DEPS_10=crf.cpp
debug/crf.o:: $(DEPS_10)
	$(RHIDE_COMPILE.cpp.o)
DEPS_11=dearfcave.cpp
debug/dearfcave.o:: $(DEPS_11)
	$(RHIDE_COMPILE.cpp.o)
DEPS_12=deity.cpp
debug/deity.o:: $(DEPS_12)
	$(RHIDE_COMPILE.cpp.o)
DEPS_13=dice.cpp
debug/dice.o:: $(DEPS_13)
	$(RHIDE_COMPILE.cpp.o)
DEPS_14=dogs.cpp
debug/dogs.o:: $(DEPS_14)
	$(RHIDE_COMPILE.cpp.o)
DEPS_15=dwarfcity.cpp
debug/dwarfcity.o:: $(DEPS_15)
	$(RHIDE_COMPILE.cpp.o)
DEPS_16=farmer.cpp
debug/farmer.o:: $(DEPS_16)
	$(RHIDE_COMPILE.cpp.o)
DEPS_17=game.cpp
debug/game.o:: $(DEPS_17)
	$(RHIDE_COMPILE.cpp.o)
DEPS_18=global.cpp
debug/global.o:: $(DEPS_18)
	$(RHIDE_COMPILE.cpp.o)
DEPS_19=goblins.cpp
debug/goblins.o:: $(DEPS_19)
	$(RHIDE_COMPILE.cpp.o)
DEPS_20=hiscore.cpp
debug/hiscore.o:: $(DEPS_20)
	$(RHIDE_COMPILE.cpp.o)
DEPS_21=humans.cpp
debug/humans.o:: $(DEPS_21)
	$(RHIDE_COMPILE.cpp.o)
DEPS_22=insects.cpp
debug/insects.o:: $(DEPS_22)
	$(RHIDE_COMPILE.cpp.o)
DEPS_23=item.cpp
debug/item.o:: $(DEPS_23)
	$(RHIDE_COMPILE.cpp.o)
DEPS_24=item_misc.cpp
debug/item_misc.o:: $(DEPS_24)
	$(RHIDE_COMPILE.cpp.o)
DEPS_25=itemdb.cpp
debug/itemdb.o:: $(DEPS_25)
	$(RHIDE_COMPILE.cpp.o)
DEPS_26=itemf.cpp
debug/itemf.o:: $(DEPS_26)
	$(RHIDE_COMPILE.cpp.o)
DEPS_27=kobolds.cpp
debug/kobolds.o:: $(DEPS_27)
	$(RHIDE_COMPILE.cpp.o)
DEPS_28=lbuilderpalette.cpp
debug/lbuilderpalette.o:: $(DEPS_28)
	$(RHIDE_COMPILE.cpp.o)
DEPS_29=ldebug.cpp
debug/ldebug.o:: $(DEPS_29)
	$(RHIDE_COMPILE.cpp.o)
DEPS_30=location.cpp
debug/location.o:: $(DEPS_30)
	$(RHIDE_COMPILE.cpp.o)
DEPS_31=los.cpp
debug/los.o:: $(DEPS_31)
	$(RHIDE_COMPILE.cpp.o)
DEPS_32=magic.cpp
debug/magic.o:: $(DEPS_32)
	$(RHIDE_COMPILE.cpp.o)
DEPS_33=main.cpp
debug/main.o:: $(DEPS_33)
	$(RHIDE_COMPILE.cpp.o)
DEPS_34=mainloc.cpp
debug/mainloc.o:: $(DEPS_34)
	$(RHIDE_COMPILE.cpp.o)
DEPS_35=manual.cpp
debug/manual.o:: $(DEPS_35)
	$(RHIDE_COMPILE.cpp.o)
DEPS_36=map.cpp
debug/map.o:: $(DEPS_36)
	$(RHIDE_COMPILE.cpp.o)
DEPS_37=modifer.cpp
debug/modifer.o:: $(DEPS_37)
	$(RHIDE_COMPILE.cpp.o)
DEPS_38=modifers.cpp
debug/modifers.o:: $(DEPS_38)
	$(RHIDE_COMPILE.cpp.o)
DEPS_39=msgwin.cpp
debug/msgwin.o:: $(DEPS_39)
	$(RHIDE_COMPILE.cpp.o)
DEPS_40=mushcave.cpp
debug/mushcave.o:: $(DEPS_40)
	$(RHIDE_COMPILE.cpp.o)
DEPS_41=orcs.cpp
debug/orcs.o:: $(DEPS_41)
	$(RHIDE_COMPILE.cpp.o)
DEPS_42=other_misc.cpp
debug/other_misc.o:: $(DEPS_42)
	$(RHIDE_COMPILE.cpp.o)
DEPS_43=people.cpp
debug/people.o:: $(DEPS_43)
	$(RHIDE_COMPILE.cpp.o)
DEPS_44=quest.cpp
debug/quest.o:: $(DEPS_44)
	$(RHIDE_COMPILE.cpp.o)
DEPS_45=rat_cell.cpp
debug/rat_cell.o:: $(DEPS_45)
	$(RHIDE_COMPILE.cpp.o)
DEPS_46=rats.cpp
debug/rats.o:: $(DEPS_46)
	$(RHIDE_COMPILE.cpp.o)
DEPS_47=rect.cpp
debug/rect.o:: $(DEPS_47)
	$(RHIDE_COMPILE.cpp.o)
DEPS_48=resist.cpp
debug/resist.o:: $(DEPS_48)
	$(RHIDE_COMPILE.cpp.o)
DEPS_49=royal_guard.cpp
debug/royal_guard.o:: $(DEPS_49)
	$(RHIDE_COMPILE.cpp.o)
DEPS_50=setting.cpp
debug/setting.o:: $(DEPS_50)
	$(RHIDE_COMPILE.cpp.o)
DEPS_51=shop.cpp
debug/shop.o:: $(DEPS_51)
	$(RHIDE_COMPILE.cpp.o)
DEPS_52=shopkeeper.cpp
debug/shopkeeper.o:: $(DEPS_52)
	$(RHIDE_COMPILE.cpp.o)
DEPS_53=skeep_ai.cpp
debug/skeep_ai.o:: $(DEPS_53)
	$(RHIDE_COMPILE.cpp.o)
DEPS_54=skill.cpp
debug/skill.o:: $(DEPS_54)
	$(RHIDE_COMPILE.cpp.o)
DEPS_55=skills.cpp
debug/skills.o:: $(DEPS_55)
	$(RHIDE_COMPILE.cpp.o)
DEPS_56=snakes.cpp
debug/snakes.o:: $(DEPS_56)
	$(RHIDE_COMPILE.cpp.o)
DEPS_57=special.cpp
debug/special.o:: $(DEPS_57)
	$(RHIDE_COMPILE.cpp.o)
DEPS_58=spell.cpp
debug/spell.o:: $(DEPS_58)
	$(RHIDE_COMPILE.cpp.o)
DEPS_59=spellfactory.cpp
debug/spellfactory.o:: $(DEPS_59)
	$(RHIDE_COMPILE.cpp.o)
DEPS_60=stats.cpp
debug/stats.o:: $(DEPS_60)
	$(RHIDE_COMPILE.cpp.o)
DEPS_61=std_ai.cpp
debug/std_ai.o:: $(DEPS_61)
	$(RHIDE_COMPILE.cpp.o)
DEPS_62=strproc.cpp
debug/strproc.o:: $(DEPS_62)
	$(RHIDE_COMPILE.cpp.o)
DEPS_63=udeadtomb.cpp
debug/udeadtomb.o:: $(DEPS_63)
	$(RHIDE_COMPILE.cpp.o)
DEPS_64=undeads.cpp
debug/undeads.o:: $(DEPS_64)
	$(RHIDE_COMPILE.cpp.o)
DEPS_65=uniquei.cpp
debug/uniquei.o:: $(DEPS_65)
	$(RHIDE_COMPILE.cpp.o)
DEPS_66=uniquem.cpp
debug/uniquem.o:: $(DEPS_66)
	$(RHIDE_COMPILE.cpp.o)
DEPS_67=wizard_dungeon.cpp
debug/wizard_dungeon.o:: $(DEPS_67)
	$(RHIDE_COMPILE.cpp.o)
DEPS_68=wmagic.cpp
debug/wmagic.o:: $(DEPS_68)
	$(RHIDE_COMPILE.cpp.o)
DEPS_69=wskills.cpp
debug/wskills.o:: $(DEPS_69)
	$(RHIDE_COMPILE.cpp.o)
DEPS_70=xamulet.cpp
debug/xamulet.o:: $(DEPS_70)
	$(RHIDE_COMPILE.cpp.o)
DEPS_71=xanyfood.cpp
debug/xanyfood.o:: $(DEPS_71)
	$(RHIDE_COMPILE.cpp.o)
DEPS_72=xanyplace.cpp
debug/xanyplace.o:: $(DEPS_72)
	$(RHIDE_COMPILE.cpp.o)
DEPS_73=xapi.cpp
debug/xapi.o:: $(DEPS_73)
	$(RHIDE_COMPILE.cpp.o)
DEPS_74=xarchive.cpp
debug/xarchive.o:: $(DEPS_74)
	$(RHIDE_COMPILE.cpp.o)
DEPS_75=xarmor.cpp
debug/xarmor.o:: $(DEPS_75)
	$(RHIDE_COMPILE.cpp.o)
DEPS_76=xbaseobj.cpp
debug/xbaseobj.o:: $(DEPS_76)
	$(RHIDE_COMPILE.cpp.o)
DEPS_77=xbasicspells.cpp
debug/xbasicspells.o:: $(DEPS_77)
	$(RHIDE_COMPILE.cpp.o)
DEPS_78=xbook.cpp
debug/xbook.o:: $(DEPS_78)
	$(RHIDE_COMPILE.cpp.o)
DEPS_79=xboots.cpp
debug/xboots.o:: $(DEPS_79)
	$(RHIDE_COMPILE.cpp.o)
DEPS_80=xcap.cpp
debug/xcap.o:: $(DEPS_80)
	$(RHIDE_COMPILE.cpp.o)
DEPS_81=xcloak.cpp
debug/xcloak.o:: $(DEPS_81)
	$(RHIDE_COMPILE.cpp.o)
DEPS_82=xclothe.cpp
debug/xclothe.o:: $(DEPS_82)
	$(RHIDE_COMPILE.cpp.o)
DEPS_83=xcorpse.cpp
debug/xcorpse.o:: $(DEPS_83)
	$(RHIDE_COMPILE.cpp.o)
DEPS_84=xenhance.cpp
debug/xenhance.o:: $(DEPS_84)
	$(RHIDE_COMPILE.cpp.o)
DEPS_85=xgen.cpp
debug/xgen.o:: $(DEPS_85)
	$(RHIDE_COMPILE.cpp.o)
DEPS_86=xgloves.cpp
debug/xgloves.o:: $(DEPS_86)
	$(RHIDE_COMPILE.cpp.o)
DEPS_87=xgui.cpp
debug/xgui.o:: $(DEPS_87)
	$(RHIDE_COMPILE.cpp.o)
DEPS_88=xherb.cpp
debug/xherb.o:: $(DEPS_88)
	$(RHIDE_COMPILE.cpp.o)
DEPS_89=xhero.cpp
debug/xhero.o:: $(DEPS_89)
	$(RHIDE_COMPILE.cpp.o)
DEPS_90=xhero2.cpp
debug/xhero2.o:: $(DEPS_90)
	$(RHIDE_COMPILE.cpp.o)
DEPS_91=xhero3.cpp
debug/xhero3.o:: $(DEPS_91)
	$(RHIDE_COMPILE.cpp.o)
DEPS_92=xmapobj.cpp
debug/xmapobj.o:: $(DEPS_92)
	$(RHIDE_COMPILE.cpp.o)
DEPS_93=xmissile.cpp
debug/xmissile.o:: $(DEPS_93)
	$(RHIDE_COMPILE.cpp.o)
DEPS_94=xmissileweapon.cpp
debug/xmissileweapon.o:: $(DEPS_94)
	$(RHIDE_COMPILE.cpp.o)
DEPS_95=xmoney.cpp
debug/xmoney.o:: $(DEPS_95)
	$(RHIDE_COMPILE.cpp.o)
DEPS_96=xobject.cpp
debug/xobject.o:: $(DEPS_96)
	$(RHIDE_COMPILE.cpp.o)
DEPS_97=xpotion.cpp
debug/xpotion.o:: $(DEPS_97)
	$(RHIDE_COMPILE.cpp.o)
DEPS_98=xration.cpp
debug/xration.o:: $(DEPS_98)
	$(RHIDE_COMPILE.cpp.o)
DEPS_99=xring.cpp
debug/xring.o:: $(DEPS_99)
	$(RHIDE_COMPILE.cpp.o)
DEPS_100=xscroll.cpp
debug/xscroll.o:: $(DEPS_100)
	$(RHIDE_COMPILE.cpp.o)
DEPS_101=xshedule.cpp
debug/xshedule.o:: $(DEPS_101)
	$(RHIDE_COMPILE.cpp.o)
DEPS_102=xshield.cpp
debug/xshield.o:: $(DEPS_102)
	$(RHIDE_COMPILE.cpp.o)
DEPS_103=xstring.cpp
debug/xstring.o:: $(DEPS_103)
	$(RHIDE_COMPILE.cpp.o)
DEPS_104=xtime.cpp
debug/xtime.o:: $(DEPS_104)
	$(RHIDE_COMPILE.cpp.o)
DEPS_105=xtool.cpp
debug/xtool.o:: $(DEPS_105)
	$(RHIDE_COMPILE.cpp.o)
DEPS_106=xweapon.cpp
debug/xweapon.o:: $(DEPS_106)
	$(RHIDE_COMPILE.cpp.o)
all:: avanor.exe
