/*
This file is part of "Avanor, the Land of Mystery" roguelike game
Home page: http://www.avanor.com/
Copyright (C) 2000-2003 Vadim Gaidukevich

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/

#ifndef ITEMDEF_H
#define ITEMDEF_H

#include <string>

enum BRAND_TYPE {
    BR_NONE	= 0x00000000,
    BR_FIRE	= 0x00000001,
    BR_HELLFIRE	= 0x00000002,
    BR_COLD	= 0x00000004,
    BR_ULTIMATECOLD	= 0x00000008,
    BR_LIGHTNING	= 0x00000010,
    BR_EARTH	= 0x00000020,
    BR_ELEMENTAL_MASK	= 0x000000FF, //mask for 'elemental'

    BR_ACID	= 0x00000100,
    BR_POISON	= 0x00000200, //cause poison
    BR_DEATH	= 0x00000400, //triple chance to score critical hit
    BR_DISEASE	= 0x00000800, //cause disease
    BR_PARALYSE	= 0x00001000,
    BR_STUN	= 0x00002000,
    BR_CONFUSE	= 0x00004000,
    BR_DRAIN_LIFE	= 0x00008000,
    BR_BLACK_MASK	= 0x0000FF00, //mask for black

    BR_UNDEADSLAYER	= 0x00010000, //3x vs undead
    BR_HUMANOIDSLAYER	= 0x00020000,
    BR_ANIMALSLAYER	= 0x00040000,
    BR_DRAGONSLAYER	= 0x00080000,
    BR_GIANTSLAYER	= 0x00100000,
    BR_ORCSLAYER	= 0x00200000,
    BR_TROLLSLAYER	= 0x00400000,
    BR_DEMONSLAYER	= 0x00800000,
    BR_SLAYER_MASK	= 0x00FF0000,

    BR_HOLYSLAYER	= BR_UNDEADSLAYER | BR_DEMONSLAYER,
    BR_EVILSLAYER	= BR_DRAGONSLAYER | BR_GIANTSLAYER | BR_ORCSLAYER | BR_TROLLSLAYER,
    BR_ANY	= 0xFFFF
};

enum CAN_FLAG {
    CAN_UNKNOWN	= 0x0000,

    CAN_BROKE	= 0x0001,
    CAN_RUST	= 0x0002,
    CAN_CORD	= 0x0004,
    CAN_DUST	= 0x0008,
    CAN_BURN	= 0x0010,
    CAN_MELT	= 0x0020,
    CAN_FROST	= 0x0040,
    CAN_LEATHERLIKE	= CAN_BURN,
    CAN_GOODMETALLIKE	= CAN_BROKE | CAN_MELT,
    CAN_BLACKMETALLIKE	= CAN_GOODMETALLIKE | CAN_CORD | CAN_RUST,
    CAN_WOODLIKE	= CAN_BROKE | CAN_BURN,
    CAN_STONELIKE	= CAN_DUST,
    CAN_POTIONLIKE	= CAN_FROST | CAN_DUST,
    CAN_PAPERLIKE	= CAN_BURN,
    CAN_FIRERESIST	= 0xffff ^ (CAN_BURN | CAN_MELT),
    CAN_COLDRESIST	= 0xffff ^ (CAN_FROST),
    CAN_ACIDRESIST	= 0xffff ^ (CAN_CORD),
    CAN_RESISTNONE	= 0xffff,
    CAN_NICEMETALLIKE	= 0,
    CAN_RESISTALL	= 0
};

enum SPECIAL_PROPERTY {
    SPP_NONE	= 0x0000,
    SPP_FASTDIGESTION	= 0x0001,
    SPP_SLOWDIGESTION	= 0x0002,
    SPP_INVISIBLE	= 0x0004,
    SPP_REGENERATION	= 0x0008
};

enum ITEM_QUALITY {
    IQ_TERRIBLE	= -4,
    IQ_VERY_BAD	= -3,
    IQ_BAD	= -2,
    IQ_POOR	= -1,
    IQ_AVG	= 0,
    IQ_FAIR	= 1,
    IQ_GOOD	= 2,
    IQ_EXCELLENT	= 3,
    IQ_SUPERB	= 4,
};

struct _ITEMPROP {
    std::string propname; //wooden, metall,
    int color;
    const char* dv; //modifers....
    const char* pv;
    const char* hit;
    const char* dice;
    const char* z; //random z to dice;
    const char* r; //range
    unsigned int iflag; //wich item can consist from this material
    int probability;
    ITEM_QUALITY iq;
    int density;
    int value;
    CAN_FLAG mflag;
    const char* resistance; //to monster
    SPECIAL_PROPERTY sp;
};

enum ITEM_SET {
    ISET_CLOTH	= 0x00000001,
    ISET_LEATHER	= 0x00000002,
    ISET_STUDEDLEATHER	= 0x00000004,
    ISET_STONE	= 0x00000008,
    ISET_WOOD	= 0x00000010,
    ISET_IRON	= 0x00000020,
    ISET_BRONZE	= 0x00000040,
    ISET_BRASS	= 0x00000080,
    ISET_SILVER	= 0x00000100,
    ISET_GOLD	= 0x00000200,
    ISET_CRYSTAL	= 0x00000400,
    ISET_STEEL	= 0x00000800,
    ISET_OBSIDIAN	= 0x00001000,
    ISET_MITHRIL	= 0x00002000,
    ISET_ADAMANTIUM	= 0x00004000,

    ISET_SOFT	= ISET_LEATHER | ISET_STUDEDLEATHER | ISET_CLOTH,
    ISET_ALLLEATHER	= ISET_LEATHER | ISET_STUDEDLEATHER,
    ISET_METAL	= ISET_IRON | ISET_BRONZE | ISET_BRASS | ISET_SILVER | ISET_GOLD,
    ISET_METALSOFT	= ISET_METAL | ISET_SOFT,
    ISET_HARDMETAL	= ISET_STEEL | ISET_MITHRIL | ISET_ADAMANTIUM,
    ISET_ALLMETAL	= ISET_METAL | ISET_HARDMETAL | ISET_OBSIDIAN,
    ISET_OBSIMETAL	= ISET_OBSIDIAN | ISET_HARDMETAL,
    ISET_STONEFROM	= ISET_STONE | ISET_CRYSTAL | ISET_OBSIDIAN,
    ISET_WOODEN	= ISET_WOOD, //wooden
    ISET_SHIELD	= ISET_ALLLEATHER | ISET_ALLMETAL | ISET_WOODEN, //for shields
    ISET_BOW	= ISET_WOODEN,
    ISET_MISSILE	= ISET_ALLMETAL | ISET_WOODEN | ISET_STONE,
    ISET_WOODSTONE	= ISET_STONEFROM | ISET_WOODEN,
    ISET_WEAPON	= ISET_STONEFROM | ISET_HARDMETAL,
    ISET_SIMPLEWEAPON = ISET_IRON | ISET_STEEL,
    ISET_CROWNMETAL	= ISET_STEEL | ISET_SILVER | ISET_GOLD | ISET_MITHRIL,
    ISET_BLACKMETAL	= ISET_STEEL | ISET_IRON,
    ISET_OTHER	= 0x0,
    ISET_ALL	= 0x00000fff | ISET_MITHRIL | ISET_ADAMANTIUM,
};

enum ITEM_TYPE {
    IT_UNKNOWN = 0,
    IT_HAT, IT_CAP, IT_HELMET,
    IT_AMULET, IT_NECKLACE,
    IT_RING,
    IT_CLUB, IT_WARHAMMER,
    IT_DAGGER, IT_KNIFE, IT_ORCISHDAGGER, IT_LONGDAGGER,
    IT_SHORTSWORD, IT_LONGSWORD, IT_BROADSWORD, IT_RAPIER, IT_SCIMITAR, IT_KATANA, IT_WAKIZASHI,
    IT_SMALLAXE, IT_WARAXE, IT_BATTLEAXE, IT_GREATAXE, IT_ORCISHAXE,
    IT_MACE, IT_FLAIL,
    IT_SHORTSPEAR, IT_LONGSPEAR, IT_PITCHFORK, IT_PIKE, IT_HALBERD,
    IT_STAFF,
    IT_SHORTBOW, IT_LONGBOW, IT_LIGHTCROSSBOW, IT_CROSSBOW, IT_HEAVYCROSSBOW, IT_SLING,
    IT_GLOVES, IT_GAUNTLETS, IT_KNUCKLES,
    IT_SMALLSHIELD, IT_MEDIUMSHIELD, IT_LARGESHIELD, IT_TOWERSHIELD,
    IT_SANDALS, IT_LIGHTBOOTS, IT_SOFTBOOTS, IT_HARDBOOTS,
    IT_CLOTHES, IT_DRESS, IT_ROBE, IT_LIGHTMAIL, IT_SCALEMAIL, IT_PLATEMAIL, IT_CHAINMAIL, IT_RINGMAIL,
    IT_CLOAK, IT_SHADOWCLOAK, IT_CAPE, IT_LIGHTCLOAK, IT_FORESTBROTHERCLOAK,
    IT_TORCH,
    IT_SCROLL,
    IT_BOOK,
    IT_POTION,
    IT_HERB,
    IT_LARGERATION, IT_RATION, IT_SMALLRATION, IT_ELVISHWAYBREAD, IT_CORPSE, IT_BONE, IT_RATTAIL, IT_BATWING,
    IT_ARROW, IT_QUARREL, IT_SLINGBULLET, IT_ROCK, IT_SHURIKEN,
    IT_COOKINGSET, IT_PICKAXE, IT_ANCIENTMACHINEPART, IT_EYEOFRAA, IT_ALCHEMYSET,
    IT_CHEST,
    IT_MONEY,
    IT_GEM,
    IT_RANDOM,
    IT_EOF
};

#endif
