-- Body armour.
--
-- Template.new(kind, type) is documented in world/items/init.lua.
--

Template.new(ItemKind.BODY, ItemType.CLOTHES)
	:View("clothes", '[')
	:Made(ItemSet.SOFT, ItemQuality.POOR)
	:Worth(3, 5)
	:Armour("1d2", "1d1")
	:Combat("", "1d1", "")
	:Chance(100)
	:Register()

Template.new(ItemKind.BODY, ItemType.DRESS)
	:View("dress", '[')
	:Made(ItemSet.SOFT, ItemQuality.POOR)
	:Worth(3, 5)
	:Armour("1d2", "1d1")
	:Combat("", "1d1", "")
	:Chance(100)
	:Register()

Template.new(ItemKind.BODY, ItemType.ROBE)
	:View("robe", '[')
	:Made(ItemSet.SOFT, ItemQuality.POOR)
	:Worth(5, 9)
	:Armour("1d2", "1d1")
	:Combat("", "1d1", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.BODY, ItemType.LIGHTMAIL)
	:View("scale mail", '[')
	:Made(ItemSet.ALLLEATHER, ItemQuality.AVG)
	:Worth(15, 15)
	:Armour("1d3+1", "1d2")
	:Combat("", "1d1", "")
	:Chance(70)
	:Register()

Template.new(ItemKind.BODY, ItemType.SCALEMAIL)
	:View("scale mail", '[')
	:Made(ItemSet.ALLMETAL, ItemQuality.FAIR)
	:Worth(30, 30)
	:Armour("1d3", "1d2+2")
	:Combat("1d2", "1d4", "")
	:Chance(20)
	:Register()

Template.new(ItemKind.BODY, ItemType.PLATEMAIL)
	:View("plate mail", '[')
	:Made(ItemSet.ALLMETAL, ItemQuality.FAIR)
	:Worth(45, 30)
	:Armour("1d3", "1d2+3")
	:Combat("1d2", "1d4", "")
	:Chance(15)
	:Register()

Template.new(ItemKind.BODY, ItemType.CHAINMAIL)
	:View("chain mail", '[')
	:Made(ItemSet.ALLMETAL, ItemQuality.GOOD)
	:Worth(45, 30)
	:Armour("1d3", "1d2+4")
	:Combat("1d2", "1d4", "")
	:Chance(10)
	:Register()

Template.new(ItemKind.BODY, ItemType.RINGMAIL)
	:View("ring mail", '[')
	:Made(ItemSet.ALLMETAL, ItemQuality.GOOD)
	:Worth(50, 30)
	:Armour("1d3", "1d2+4")
	:Combat("1d2", "1d4", "")
	:Chance(10)
	:Register()
