-- Bows, crossbows and slings.
--
-- Template.new(kind, type) is documented in world/items/init.lua.
--

Template.new(ItemKind.MISSILEW, ItemType.LONGBOW)
	:View("long bow", '{')
	:Made(ItemSet.BOW, ItemQuality.FAIR)
	:Skill(XWarSkills.BOW)
	:Worth(20, 10)
	:Combat("1d3+2", "1d6", "1d3+2")
	:Range("1d1+2")
	:Chance(30)
	:Register()

Template.new(ItemKind.MISSILEW, ItemType.SHORTBOW)
	:View("short bow", '{')
	:Made(ItemSet.BOW, ItemQuality.AVG)
	:Skill(XWarSkills.BOW)
	:Worth(10, 5)
	:Combat("1d2", "1d4", "1d2")
	:Range("1d2")
	:Chance(150)
	:Register()

Template.new(ItemKind.MISSILEW, ItemType.LIGHTCROSSBOW)
	:View("light crossbow", '{')
	:Made(ItemSet.BOW, ItemQuality.AVG)
	:Skill(XWarSkills.CROSSBOW)
	:Worth(10, 5)
	:Combat("1d2", "1d5", "1d3")
	:Range("1d2")
	:Chance(120)
	:Register()

Template.new(ItemKind.MISSILEW, ItemType.CROSSBOW)
	:View("crossbow", '{')
	:Made(ItemSet.BOW, ItemQuality.AVG)
	:Skill(XWarSkills.CROSSBOW)
	:Worth(15, 5)
	:Combat("1d4", "1d6", "1d3+1")
	:Range("1d2")
	:Chance(70)
	:Register()

Template.new(ItemKind.MISSILEW, ItemType.HEAVYCROSSBOW)
	:View("heavy crossbow", '{')
	:Made(ItemSet.BOW, ItemQuality.GOOD)
	:Skill(XWarSkills.CROSSBOW)
	:Worth(35, 30)
	:Combat("1d3", "1d8", "1d4+2")
	:Range("1d2+1")
	:Chance(10)
	:Register()

Template.new(ItemKind.MISSILEW, ItemType.SLING)
	:View("sling", '{')
	:Made(ItemSet.ALLLEATHER, ItemQuality.POOR)
	:Skill(XWarSkills.SLING)
	:Worth(5, 2)
	:Combat("1d2", "1d3+1", "1d3")
	:Range("1d1+1")
	:Chance(200)
	:Register()
