-- Weapons: everything the game may hand out as a weapon, and how
-- often. The war skill each sort trains is a rule rather than a figure,
-- and stays in C++ (wbind, item/xweapon.cpp).
--
-- Template.new(kind, type) is documented in world/items/init.lua.
--

Template.new(ItemKind.WEAPON, "club")
	:View("club", '/')
	:Made(ItemSet.WOODSTONE, ItemQuality.POOR)
	:Skill("club")
	:Verb("smash")
	:Worth(1, 10)
	:Combat("", "1d3", "")
	:Chance(200)
	:Register()

Template.new(ItemKind.WEAPON, "war_hammer")
	:View("war hammer", '/')
	:Made(ItemSet.HARDMETAL, ItemQuality.AVG)
	:Skill("club")
	:Verb("smash")
	:Worth(12, 10)
	:Combat("1d2", "1d7", "1d4")
	:Chance(50)
	:Register()

Template.new(ItemKind.WEAPON, "dagger")
	:View("dagger", '/')
	:Made(ItemSet.WEAPON, ItemQuality.AVG)
	:Skill("dagger")
	:Worth(2, 3)
	:Combat("", "1d4", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.WEAPON, "knife")
	:View("knife", '/')
	:Made(ItemSet.SIMPLEWEAPON, ItemQuality.POOR)
	:Skill("dagger")
	:Worth(1, 2)
	:Combat("1d2", "1d3", "")
	:Chance(200)
	:Register()

Template.new(ItemKind.WEAPON, "orcish_dagger")
	:View("orcish dagger", '/')
	:Made(ItemSet.STEEL, ItemQuality.AVG)
	:Skill("dagger")
	:Worth(3, 3)
	:Combat("1d2+1", "1d3", "1d2+2")
	:Chance(70)
	:Register()

Template.new(ItemKind.WEAPON, "long_dagger")
	:View("long dagger", '/')
	:Made(ItemSet.STEEL, ItemQuality.FAIR)
	:Skill("dagger")
	:Worth(4, 3)
	:Combat("1d3", "1d4", "1d2+1")
	:Chance(50)
	:Register()

Template.new(ItemKind.WEAPON, "short_sword")
	:View("short sword", '/')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill("sword")
	:Worth(6, 5)
	:Combat("", "1d5", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.WEAPON, "long_sword")
	:View("long sword", '|')
	:Made(ItemSet.OBSIMETAL, ItemQuality.FAIR)
	:Skill("sword")
	:Worth(18, 10)
	:Combat("", "2d4", "")
	:Chance(60)
	:Register()

Template.new(ItemKind.WEAPON, "broad_sword")
	:View("broad sword", '|')
	:Made(ItemSet.OBSIMETAL, ItemQuality.FAIR)
	:Skill("sword")
	:Worth(20, 12)
	:Combat("", "2d5", "")
	:Chance(30)
	:Register()

Template.new(ItemKind.WEAPON, "rapier")
	:View("rapier", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill("sword")
	:Worth(7, 5)
	:Combat("1d3+2", "1d6", "")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, "scimitar")
	:View("scimitar", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill("sword")
	:Worth(7, 6)
	:Combat("1d4", "1d6", "1d3")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, "katana")
	:View("katana", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.GOOD)
	:Skill("sword")
	:Worth(50, 1)
	:Combat("1d5+5", "4d2", "1d3+2")
	:Chance(50)
	:Register()

Template.new(ItemKind.WEAPON, "wakizashi")
	:View("wakizashi", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill("sword")
	:Worth(45, 1)
	:Combat("1d5+3", "3d2", "1d3+1")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, "small_axe")
	:View("small axe", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill("axe")
	:Verb("hack")
	:Worth(10, 6)
	:Combat("", "1d6", "")
	:Chance(120)
	:Register()

Template.new(ItemKind.WEAPON, "war_axe")
	:View("war axe", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill("axe")
	:Verb("hack")
	:Worth(15, 7)
	:Combat("1d3+1", "2d3", "")
	:Chance(90)
	:Register()

Template.new(ItemKind.WEAPON, "battle_axe")
	:View("battle axe", '\\')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill("axe")
	:Verb("hack")
	:Worth(25, 12)
	:Combat("1d3+2", "2d5", "1d3+1")
	:Chance(70)
	:Register()

Template.new(ItemKind.WEAPON, "great_axe")
	:View("great axe", '\\')
	:Made(ItemSet.HARDMETAL, ItemQuality.GOOD)
	:Skill("axe")
	:Verb("hack")
	:Worth(30, 20)
	:Combat("1d5", "3d4", "1d4+3")
	:Chance(20)
	:Register()

Template.new(ItemKind.WEAPON, "orcish_axe")
	:View("orcish axe", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill("axe")
	:Verb("hack")
	:Worth(10, 10)
	:Combat("1d3+1", "2d4", "1d2+2")
	:Chance(90)
	:Register()

Template.new(ItemKind.WEAPON, "mace")
	:View("mace", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill("mace")
	:Verb("smash")
	:Worth(10, 7)
	:Combat("", "1d6", "")
	:Chance(100)
	:Register()

Template.new(ItemKind.WEAPON, "flail")
	:View("flail", '\\')
	:Made(ItemSet.HARDMETAL, ItemQuality.AVG)
	:Skill("mace")
	:Verb("smash")
	:Worth(15, 7)
	:Combat("", "1d7", "")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, "short_spear")
	:View("short spear", '/')
	:Made(ItemSet.WOODSTONE, ItemQuality.POOR)
	:Skill("polearm")
	:Worth(3, 4)
	:Combat("", "1d5", "")
	:Chance(300)
	:Register()

Template.new(ItemKind.WEAPON, "long_spear")
	:View("long spear", '/')
	:Made(ItemSet.STEEL, ItemQuality.AVG)
	:Skill("polearm")
	:Worth(8, 6)
	:Combat("", "1d9", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.WEAPON, "pitchfork")
	:View("pitchfork", '/')
	:Made(ItemSet.BLACKMETAL, ItemQuality.POOR)
	:Skill("polearm")
	:Worth(1, 3)
	:Combat("1d2", "1d3", "")
	:Chance(300)
	:Register()

Template.new(ItemKind.WEAPON, "pike")
	:View("pike", '/')
	:Made(ItemSet.BLACKMETAL, ItemQuality.AVG)
	:Skill("polearm")
	:Worth(1, 3)
	:Combat("1d3", "1d10", "1d4+2")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, "halberd")
	:View("halberd", '/')
	:Made(ItemSet.HARDMETAL, ItemQuality.GOOD)
	:Skill("polearm")
	:Worth(1, 3)
	:Combat("1d3", "1d12", "1d4+3")
	:Chance(30)
	:Register()

Template.new(ItemKind.WEAPON, "staff")
	:View("staff", '/')
	:Made(ItemSet.WOOD, ItemQuality.AVG)
	:Skill("stave")
	:Worth(8, 3)
	:Combat("1d2", "1d10", "1d2")
	:Chance(100)
	:Register()
