-- Weapons: everything the game may hand out as a weapon, and how
-- often. The war skill each sort trains is a rule rather than a figure,
-- and stays in C++ (wbind, item/xweapon.cpp).
--
-- Template.new(kind, type) is documented in world/items/init.lua.
--

Template.new(ItemKind.WEAPON, ItemType.CLUB)
	:View("club", '/')
	:Made(ItemSet.WOODSTONE, ItemQuality.POOR)
	:Skill(XWarSkills.CLUB)
	:Verb("smash")
	:Worth(1, 10)
	:Combat("", "1d3", "")
	:Chance(200)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.WARHAMMER)
	:View("war hammer", '/')
	:Made(ItemSet.HARDMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.CLUB)
	:Verb("smash")
	:Worth(12, 10)
	:Combat("1d2", "1d7", "1d4")
	:Chance(50)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.DAGGER)
	:View("dagger", '/')
	:Made(ItemSet.WEAPON, ItemQuality.AVG)
	:Skill(XWarSkills.DAGGER)
	:Worth(2, 3)
	:Combat("", "1d4", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.KNIFE)
	:View("knife", '/')
	:Made(ItemSet.SIMPLEWEAPON, ItemQuality.POOR)
	:Skill(XWarSkills.DAGGER)
	:Worth(1, 2)
	:Combat("1d2", "1d3", "")
	:Chance(200)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.ORCISHDAGGER)
	:View("orcish dagger", '/')
	:Made(ItemSet.STEEL, ItemQuality.AVG)
	:Skill(XWarSkills.DAGGER)
	:Worth(3, 3)
	:Combat("1d2+1", "1d3", "1d2+2")
	:Chance(70)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.LONGDAGGER)
	:View("long dagger", '/')
	:Made(ItemSet.STEEL, ItemQuality.FAIR)
	:Skill(XWarSkills.DAGGER)
	:Worth(4, 3)
	:Combat("1d3", "1d4", "1d2+1")
	:Chance(50)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.SHORTSWORD)
	:View("short sword", '/')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.SWORD)
	:Worth(6, 5)
	:Combat("", "1d5", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.LONGSWORD)
	:View("long sword", '|')
	:Made(ItemSet.OBSIMETAL, ItemQuality.FAIR)
	:Skill(XWarSkills.SWORD)
	:Worth(18, 10)
	:Combat("", "2d4", "")
	:Chance(60)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.BROADSWORD)
	:View("broad sword", '|')
	:Made(ItemSet.OBSIMETAL, ItemQuality.FAIR)
	:Skill(XWarSkills.SWORD)
	:Worth(20, 12)
	:Combat("", "2d5", "")
	:Chance(30)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.RAPIER)
	:View("rapier", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill(XWarSkills.SWORD)
	:Worth(7, 5)
	:Combat("1d3+2", "1d6", "")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.SCIMITAR)
	:View("scimitar", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill(XWarSkills.SWORD)
	:Worth(7, 6)
	:Combat("1d4", "1d6", "1d3")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.KATANA)
	:View("katana", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.GOOD)
	:Skill(XWarSkills.SWORD)
	:Worth(50, 1)
	:Combat("1d5+5", "4d2", "1d3+2")
	:Chance(50)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.WAKIZASHI)
	:View("wakizashi", '|')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill(XWarSkills.SWORD)
	:Worth(45, 1)
	:Combat("1d5+3", "3d2", "1d3+1")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.SMALLAXE)
	:View("small axe", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.AXE)
	:Verb("hack")
	:Worth(10, 6)
	:Combat("", "1d6", "")
	:Chance(120)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.WARAXE)
	:View("war axe", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.AXE)
	:Verb("hack")
	:Worth(15, 7)
	:Combat("1d3+1", "2d3", "")
	:Chance(90)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.BATTLEAXE)
	:View("battle axe", '\\')
	:Made(ItemSet.HARDMETAL, ItemQuality.FAIR)
	:Skill(XWarSkills.AXE)
	:Verb("hack")
	:Worth(25, 12)
	:Combat("1d3+2", "2d5", "1d3+1")
	:Chance(70)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.GREATAXE)
	:View("great axe", '\\')
	:Made(ItemSet.HARDMETAL, ItemQuality.GOOD)
	:Skill(XWarSkills.AXE)
	:Verb("hack")
	:Worth(30, 20)
	:Combat("1d5", "3d4", "1d4+3")
	:Chance(20)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.ORCISHAXE)
	:View("orcish axe", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.AXE)
	:Verb("hack")
	:Worth(10, 10)
	:Combat("1d3+1", "2d4", "1d2+2")
	:Chance(90)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.MACE)
	:View("mace", '\\')
	:Made(ItemSet.OBSIMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.MACE)
	:Verb("smash")
	:Worth(10, 7)
	:Combat("", "1d6", "")
	:Chance(100)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.FLAIL)
	:View("flail", '\\')
	:Made(ItemSet.HARDMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.MACE)
	:Verb("smash")
	:Worth(15, 7)
	:Combat("", "1d7", "")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.SHORTSPEAR)
	:View("short spear", '/')
	:Made(ItemSet.WOODSTONE, ItemQuality.POOR)
	:Skill(XWarSkills.POLEARM)
	:Worth(3, 4)
	:Combat("", "1d5", "")
	:Chance(300)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.LONGSPEAR)
	:View("long spear", '/')
	:Made(ItemSet.STEEL, ItemQuality.AVG)
	:Skill(XWarSkills.POLEARM)
	:Worth(8, 6)
	:Combat("", "1d9", "")
	:Chance(150)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.PITCHFORK)
	:View("pitchfork", '/')
	:Made(ItemSet.BLACKMETAL, ItemQuality.POOR)
	:Skill(XWarSkills.POLEARM)
	:Worth(1, 3)
	:Combat("1d2", "1d3", "")
	:Chance(300)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.PIKE)
	:View("pike", '/')
	:Made(ItemSet.BLACKMETAL, ItemQuality.AVG)
	:Skill(XWarSkills.POLEARM)
	:Worth(1, 3)
	:Combat("1d3", "1d10", "1d4+2")
	:Chance(80)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.HALBERD)
	:View("halberd", '/')
	:Made(ItemSet.HARDMETAL, ItemQuality.GOOD)
	:Skill(XWarSkills.POLEARM)
	:Worth(1, 3)
	:Combat("1d3", "1d12", "1d4+3")
	:Chance(30)
	:Register()

Template.new(ItemKind.WEAPON, ItemType.STAFF)
	:View("staff", '/')
	:Made(ItemSet.WOOD, ItemQuality.AVG)
	:Skill(XWarSkills.STAVE)
	:Worth(8, 3)
	:Combat("1d2", "1d10", "1d2")
	:Chance(100)
	:Register()
