------------------------------ CANINE --------------------------------------

	Monster.new("dog")
		:View("dog", 'C', xColor.xBROWN, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.CANINE)
		:Basic("1d10+100", "0d0+1000", "1d100+900", CS_SMALL, "1d100+200")
		:Body("", 0, 0)
		:AI(XStandardAI.HI_ANIMAL + XStandardAI.ALLOW_PACK + XStandardAI.ALLOW_PACK)
		:Stats("St 2d3 Dx 2d3 To 1d3 Le 1d1 Wi 1d1 Ma 1d1 Pe 3d3 Ch 1d1")
		:Resist("fire:5d5-40 cold:5d10")
		:Combat("1d2", "2d3")
		:Main("1d4", "1d2", "2d3", "0d0")
		:Description("Dogs were brought to the valley of Avanor to serve the residents of the kingdom, but some of them escaped and became feral and breeding in the caves below the surface.  Mongrels in every sense, these animals now prey upon other creatures for food, including silly adventurers.")
		:Register()

	Monster.new("large_dog")
		:View("large dog", 'C', xColor.xBROWN, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.CANINE)
		:Basic("1d10+100", "0d0+1000", "1d100+900", CS_SMALL, "1d200+300")
		:Body("", 0, 0)
		:AI(XStandardAI.HI_ANIMAL + XStandardAI.ALLOW_PACK + XStandardAI.ALLOW_PACK)
		:Stats("St 2d4 Dx 2d4 To 2d2 Le 1d1 Wi 1d1 Ma 1d1 Pe 3d3 Ch 1d1")
		:Resist("fire:5d5-30 cold:6d10")
		:Combat("1d4", "2d4")
		:Main("1d4", "1d3", "2d4", "0d0")
		:Description("Obviously the leader of his pack, this dog is larger than the others and may be the offspring of a dog and a wolf.  Its muzzle and body are scarred from numerous fights and it limps slightly.  The deference the other dogs show it indicates that it is still a dangerous foe.")
		:Register()

	Monster.new("rabid_dog")
		:View("rabid dog", 'C', xColor.xBROWN, PersonType.IT, CreatureTemplate.LOW, CreatureClass.CANINE)
		:Basic("1d10+120", "0d0+1000", "1d100+700", CS_SMALL, "1d100+200")
		:Body("", 0, 0)
		:AI(XStandardAI.HI_ANIMAL + XStandardAI.ALLOW_PACK)
		:Stats("St 2d4 Dx 2d2 To 1d2 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d3 Ch 1d1")
		:Resist("fire:5d5-30 cold:4d10")
		:Combat("2d4", "2d3")
		:Main("1d2", "1d1", "2d3", "0d0")
		:Description("White foam drips from the jaws of this dog.  The wild look in its eyes indicate that something is not quite right, and it snaps at everything and everyone around it with the strength born of its diseased madness.")
		:Melee(AttackEffectType.DISEASE, 50)
		:CorpseEffect(CET_DISEASE, 50)
		:Register()

	Monster.new("wolf")
		:View("wolf", 'C', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.CANINE)
		:Basic("1d10+130", "0d0+1000", "1d100+700", CS_SMALL, "1d300+500")
		:Body("", 0, 0)
		:AI(XStandardAI.HI_ANIMAL + XStandardAI.ALLOW_PACK)
		:Stats("St 4d3+2 Dx 2d4+1 To 2d3 Le 1d1 Wi 1d1 Ma 1d1 Pe 3d4 Ch 1d1")
		:Resist("fire:5d5-20 cold:7d10")
		:Combat("3d4", "2d6")
		:Main("2d4", "2d3", "3d4", "0d0")
		:Description("One glance at this wolf tells you why it has come down from the mountains... to look for food.  The shaggy pelt and thin body are proof of hard times since the eruption of Power.")
		:Register()

	Monster.new("large_wolf")
		:View("large wolf", 'C', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.AVG, CreatureClass.CANINE)
		:Basic("1d10+130", "0d0+1000", "1d100+700", CS_NORMAL, "1d300+700")
		:Body("", 0, 0)
		:AI(XStandardAI.HI_ANIMAL + XStandardAI.ALLOW_PACK)
		:Stats("St 4d4+2 Dx 3d4+1 To 3d4 Le 1d1 Wi 1d1 Ma 1d1 Pe 3d4 Ch 1d1")
		:Resist("cold:9d10")
		:Combat("5d5", "3d6")
		:Main("2d4", "3d3", "5d4", "0d0")
		:Description("This wolf is almost the size of a small pony.  It is fast, strong and eager to eat anything smaller than itself.  Its hungry gaze makes you uncomfortable as it faces you with fangs bared.")
		:Register()

	Monster.new("werewolf")
		:View("werewolf", 'C', xColor.xDARKGRAY, PersonType.IT, CreatureTemplate.HI, CreatureClass.CANINE)
		:Basic("1d10+150", "0d0+1000", "1d100+500", CS_NORMAL, "1d300+1000")
		:Body("", 0, 0)
		:AI(XStandardAI.HI_ANIMAL)
		:Stats("St 7d4 Dx 5d4 To 5d4 Le 1d1 Wi 1d1 Ma 1d1 Pe 5d4 Ch 1d1")
		:Resist("fire:4d10 cold:9d10")
		:Combat("6d5", "4d6")
		:Main("2d8", "3d4", "7d4", "7d4")
		:Description("As you gaze on this creature its features shift from wolf to man and back again.  Product of a dreadful experiment in magic, the werewolf hunts in the caves of Avanor for food.  It is said that silver weapons are the only true way to defeat a werewolf.")
		:Melee(AttackEffectType.DISEASE, 100)
		:Melee(AttackEffectType.PARALYSE, 20)
		:CorpseEffect(CET_PARALYSE, 50)
		:CorpseEffect(CET_MODIFY_R_PARALYSE, 5)
		:CorpseEffect(CET_DISEASE, 50)
		:Register()
