------------------------------ HUMANS & HUMANOIDS --------------------------------------

	Monster.new("farmer")
		:View("farmer", 'p', xColor.xBROWN, PersonType.HE, CreatureTemplate.VERY_LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 0, CreatureTemplate.SUPPRESS_INVIS)
		:AI(XStandardAI.HUMAN + XStandardAI.PEACEFUL)
		:Stats("St 2d3 Dx 2d3 To 1d3 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6+6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3+1", "2d2")
		:Description("The sunburnt face and arms of this fellow, as well as the pitchfork he leans upon give no doubt as to his profession.  He and his fellows produce and gather the food for the entire valley.")
		:LearnSkill(SKT_HEALING, 2)
		:Equip(ItemKind.WEAPON, ItemType.PITCHFORK, 100)
		:Equip(ItemKind.BODY, ItemType.ROBE, 100)
		:Register()

	Monster.new("goodwife")
		:View("goodwife", 'p', xColor.xYELLOW, PersonType.SHE, CreatureTemplate.VERY_LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 0, CreatureTemplate.SUPPRESS_INVIS)
		:AI(XStandardAI.HUMAN + XStandardAI.PEACEFUL)
		:Stats("St 2d3 Dx 2d3 To 1d3 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6+6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3+1", "2d2")
		:Description("This woman's clothing tells a story of a simple but hard life.  She prepares the meals for her husband every day and takes care of their cottage.")
		:LearnSkill(SKT_HEALING, 2)
		:Equip(ItemKind.BODY, ItemType.DRESS, 100)
		:Register()


	Monster.new("bandit")
		:View("bandit", 'p', xColor.xLIGHTGRAY, PersonType.HE, CreatureTemplate.LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 50, 0)
		:AI(XStandardAI.HUMAN)
		:Stats("St 1d4+10 Dx 1d4+10 To 1d4+10 Le 1d4+10 Wi 1d4+10 Ma 1d4+10 Pe 1d4+15 Ch 1d4+10")
		:Resist("")
		:Combat("1d4", "1d3")
		:Main("1d4", "0d0", "1d4+10", "2d5")
		:Description("A scruffy looking fellow, he looks much like any citizen of the valley except for the green cape, the twin daggers and the malicious glint in his eye.  You get the distinct impression that he would rob his own mother if she had anything worth taking.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 30)
		:Equip(ItemKind.WEAPON, ItemType.LONGDAGGER, 100)
		:Equip(ItemKind.WEAPON, ItemType.LONGDAGGER, 100)
		:Unique()
		:Register()

	Monster.new("citizen")
		:View("citizen", 'p', xColor.xLIGHTGRAY, PersonType.HE, CreatureTemplate.VERY_LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 0, CreatureTemplate.SUPPRESS_INVIS)
		:AI(XStandardAI.HUMAN + XStandardAI.PEACEFUL)
		:Stats("St 2d3 Dx 2d3 To 1d3 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6+6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3+1", "2d2")
		:Description("This upstanding citizen of the castle of Avanor hurries about the duties of the day.  The calm relaxed confidence surrounding him demonstrates his faith in the forces of the guard and the king to protect him and his family.")
		:Equip(ItemKind.BODY, ItemType.CLOTHES, 100)
		:Register()

	Monster.new("fcitizen")
		:View("citizen", 'p', xColor.xLIGHTGRAY, PersonType.SHE, CreatureTemplate.VERY_LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 0, CreatureTemplate.SUPPRESS_INVIS)
		:AI(XStandardAI.HUMAN + XStandardAI.PEACEFUL)
		:Stats("St 2d3 Dx 2d3 To 1d3 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6+6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3+1", "2d2")
		:Description("This upstanding citizen of the castle of Avanor hurries about the duties of the day.  The calm relaxed confidence surrounding her demonstrates her faith in the forces of the guard and the king to protect her and her family.")
		:Equip(ItemKind.BODY, ItemType.DRESS, 100)
		:Register()

	Monster.new("royal_guard")
		:View("royal guardian", 'p', xColor.xBLUE, PersonType.HE, CreatureTemplate.LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 50, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.HUMAN + XStandardAI.PEACEFUL)
		:Stats("St 1d8+15 Dx 1d8+20 To 1d8+10 Le 1d5+10 Wi 1d4+5 Ma 1d4+5 Pe 3d6 Ch 5d5")
		:Resist("")
		:Combat("1d6", "2d2")
		:Main("3d2", "1d2", "1d5+10", "1d3+5")
		:Description("The elite guard of Avanor was organized by King Rodrick to protect citizens from the depradations of bandits and the monsters that live in the valley.  Every child dreams of someday serving in the King's guard.  Royal Guardians are well equipped to protect the people and themselves.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:Equip(ItemKind.WEAPON, ItemType.LONGSWORD, 100)
		:Equip(ItemKind.SHIELD, ItemType.TOWERSHIELD, 100)
		:Register()

	Monster.new("death_knight")
		:View("death knight", 'p', xColor.xDARKGRAY, PersonType.HE, CreatureTemplate.LOW, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 50, 0)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD)
		:Stats("St 1d8+20 Dx 1d8+20 To 1d8+10 Le 1d5+10 Wi 1d4+5 Ma 1d4+5 Pe 3d6 Ch 5d5")
		:Resist("")
		:Combat("1d6", "2d2")
		:Main("3d2", "1d2", "1d5+10", "1d3+5")
		:Description("The elite guard of Ahk-Ulan the sorcerer.  Deprived of all human emotion, they have become finely tuned killing machines who worship only death.  The stench of blood surrounds them and their soulless gaze makes your flesh crawl.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:Equip(ItemKind.WEAPON, ItemType.LONGSWORD, 100)
		:Equip(ItemKind.SHIELD, ItemType.TOWERSHIELD, 100)
		:Register()

	Monster.new("shopkeeper")
		:View("shopkeeper", 'p', xColor.xLIGHTGRAY, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d10+120", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+20 Dx 1d8+20 To 1d8+20 Le 1d5+20 Wi 1d4+20 Ma 1d4+20 Pe 3d6 Ch 5d5")
		:Resist("")
		:Combat("1d6", "2d2")
		:Main("3d2", "1d2", "1d5+10", "1d3+5")
		:Description("It takes a special breed to set up shop in this remote valley.  Shopkeepers must be able to defend their wares as well as chat amiably with customers.  Behind the cheery exterior is a sharp intelligence and well toned muscles.  Only the desperate or the foolish would try to steal from one of them.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:Unique()
		:Register()

	Monster.new("dwarf")
		:View("dwarf", 'h', xColor.xBROWN, PersonType.HE, CreatureTemplate.VERY_LOW, CreatureClass.HUMANOID)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 50, 0)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d3+10 Dx 1d3+7 To 1d3+12 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3+1", "2d2")
		:Description("Standing only about 4 feet high, dwarves are known to be master diggers and metal workers.  With a beard starting right below the merrily twinkling eyes, the dwarf whistles a lively tune as he goes about his business.  The axe stuck in his belt and his easy balance indicate that he can be a formidable warrior in times of danger.")
		:Register()

	Monster.new("dwarf_guard")
		:View("dwarven guardian", 'h', xColor.xLIGHTBLUE, PersonType.HE, CreatureTemplate.VERY_LOW, CreatureClass.HUMANOID)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 50, CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d3+20 Dx 1d3+7 To 1d3+22 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3+1", "2d2")
		:Description("Guardians of the underground dwarven city, these dwarves are well armed and prepared for any breach of security both physical and magical.  Only a fool would attempt to accost one as he goes about his duties.  The cold glare and cold steel they carry is usually more than enough to keep trouble makers in line.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
		:Equip(ItemKind.SHIELD, ItemType.LARGESHIELD, 100)
		:Register()
