------------------------------ INSECTS --------------------------------------

Monster.new("spider")
	:View("spider", 'S', xColor.xBROWN, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.INSECT)
	:Basic("1d10+70", "0d0+1000", "1d100+900", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d30-50 cold:1d20-40")
	:Combat("2d5", "1d2")
	:Main("1d1", "0d0", "1d2", "0d0")
	:Description("A foot wide and covered with grayish brown hair, this spider contemplates you with its eight eyes.  Spiders like this one have filled the corners of the caves of Avanor with webs.  Usually just a nuisance, some of them are equipped with deadly venom.")
	:Register()

Monster.new("giant_spider")
	:View("giant spider", 'S', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.INSECT)
	:Basic("1d10+80", "0d0+1000", "1d100+600", CS_VERY_SMALL, "1d10+10")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d2 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d30-50 cold:1d20-40")
	:Combat("3d5", "1d3")
	:Main("1d2", "0d0", "1d3", "0d0")
	:Description("These eight legged monstrosities escaped from a long dead wizard's laboratory and made homes in the deep caves of the mountains surrounding the valley.  Their webs are capable of ensnaring an unwary adventurer and their venom can be quite deadly.")
	:Melee(AttackEffectType.POISON, 15)
	:CorpseEffect(CET_MODIFY_R_POISON, 1)
	:CorpseEffect(CET_POISON, 10)
	:Register()

Monster.new("tarantula")
	:View("tarantula", 'S', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.INSECT)
	:Basic("1d10+70", "0d0+1000", "1d100+600", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d30-50 cold:1d20-60")
	:Combat("3d5", "1d6")
	:Main("1d1", "0d0", "1d3", "0d0")
	:Description("These spiders live in nooks and crannies in the rock and can pop into view when least expected.  Unable to spin webs, they rely on brute strength and venom to overcome a victim.  Creatures may be paralyzed by their venom only to be hauled back to a hole and eaten alive by the tarantula's young.")
	:Melee(AttackEffectType.POISON, 40)
	:Melee(AttackEffectType.PARALYSE, 10)
	:CorpseEffect(CET_MODIFY_R_POISON, 2)
	:CorpseEffect(CET_POISON, 15)
	:Register()

Monster.new("scorpion")
	:View("scorpion", 'S', xColor.xYELLOW, PersonType.IT, CreatureTemplate.LOW, CreatureClass.INSECT)
	:Basic("1d10+70", "0d0+1000", "1d100+600", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d30-50 cold:1d20-60")
	:Combat("5d5", "1d6")
	:Main("1d1", "0d0", "1d5", "0d0")
	:Description("This creature is a foot long and colored a dusty brown with a tail arching high over it's back.  Scorpions use the poison in their stinging tail as well as formidable pincers as a powerful attack.  They also have a strong exoskeleton which protects them from many attacks.")
	:Melee(AttackEffectType.POISON, 60)
	:Melee(AttackEffectType.PARALYSE, 20)
	:CorpseEffect(CET_MODIFY_R_POISON, 3)
	:CorpseEffect(CET_POISON, 20)
	:CorpseEffect(CET_PARALYSE, 20)
	:Register()

Monster.new("black_scorpion")
	:View("black scorpion", 'S', xColor.xDARKGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.INSECT)
	:Basic("1d10+70", "0d0+1000", "1d100+600", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d30-50 cold:1d20-60")
	:Combat("10d5", "1d10")
	:Main("1d1", "0d0", "1d7", "0d0")
	:Description("Black scorpions hide in the shadows of caves and will often flee from a light source.  When cornered, they fight with both pincers and their tail with great agility.  Though not as strong as their dusty cousins, they do move quite a bit faster.")
	:Melee(AttackEffectType.POISON, 80)
	:Melee(AttackEffectType.PARALYSE, 30)
	:CorpseEffect(CET_MODIFY_R_POISON, 5)
	:CorpseEffect(CET_POISON, 30)
	:CorpseEffect(CET_PARALYSE, 30)
	:Register()

Monster.new("pink_scorpion")
	:View("pink scorpion", 'S', xColor.xLIGHTMAGENTA, PersonType.IT, CreatureTemplate.AVG, CreatureClass.INSECT)
	:Basic("1d10+70", "0d0+1000", "1d100+600", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d30-50 cold:1d20-60")
	:Combat("20d5", "1d20")
	:Main("1d1", "0d0", "1d9", "0d0")
	:Description("This scorpion originally evolved with this coloring in order to hide among plant flowers and surprise prey.  These scorpions are extremely aggressive and dangerous.  Sometimes they still carry exotic pollen from the flowers on the tip of their tails.")
	:Melee(AttackEffectType.POISON, 100)
	:Melee(AttackEffectType.PARALYSE, 40)
	:Melee(AttackEffectType.STUN, 40)
	:Melee(AttackEffectType.CONFUSE, 40)
	:CorpseEffect(CET_MODIFY_R_POISON, 10)
	:CorpseEffect(CET_POISON, 50)
	:CorpseEffect(CET_PARALYSE, 50)
	:Register()


Monster.new("fire_beetle")
	:View("fire beetle", 'i', xColor.xRED, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.INSECT)
	:Basic("1d10+100", "0d0+1000", "1d300+900", CS_VERY_SMALL, "5d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d3 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d90 cold:1d20-80")
	:Combat("1d3", "1d3")
	:Main("1d1", "1d8", "1d3", "0d0")
	:Description("Usually living only in depths of the earth, fire beetles were drawn to the surface by the intense energies used to raise the mountains surrounding Avanor.  Their normal habitat has made them immune to great heat and their thick exo-skeleton protects them from many physical attacks.")
	:Melee(AttackEffectType.FIRE, 100)
	:CorpseEffect(CET_MODIFY_R_FIRE, 2)
	:CorpseEffect(CET_MODIFY_R_COLD, -1)
	:Register()


Monster.new("frost_beetle")
	:View("frost beetle", 'i', xColor.xWHITE, PersonType.IT, CreatureTemplate.LOW, CreatureClass.INSECT)
	:Basic("1d10+110", "0d0+1000", "1d300+900", CS_VERY_SMALL, "7d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d3 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("fire:1d20-80 cold:1d80")
	:Combat("1d5", "1d10")
	:Main("1d1", "4d4", "1d5", "0d0")
	:Description("Frost beetles are characterized by a white shell and faint blue markings.  They usually live high in the mountains upon snow capped peaks.  With the release of power in the mountain chain, many of them fled to the caverns below to seek shelter.  They are immune to cold attacks and their thick exo-skeleton protects them from many physical attacks.")
	:Melee(AttackEffectType.COLD, 100)
	:CorpseEffect(CET_MODIFY_R_COLD, 2)
	:CorpseEffect(CET_MODIFY_R_FIRE, -1)
	:Register()


Monster.new("green_beetle")
	:View("green beetle", 'i', xColor.xGREEN, PersonType.IT, CreatureTemplate.LOW, CreatureClass.INSECT)
	:Basic("1d10+120", "0d0+1000", "1d300+900", CS_VERY_SMALL, "7d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d5 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("acid:1d80")
	:Combat("1d5", "1d12")
	:Main("1d1", "5d4", "1d8", "0d0")
	:Description("Green beetles are often seen in packs.  Their exo-skeleton is not as tough as the frost or fire beetle, but they are able to shoot streams of acid at their target with great accuracy.")
	:Melee(AttackEffectType.ACID, 100)
	:CorpseEffect(CET_MODIFY_R_ACID, 2)
	:CorpseEffect(CET_MODIFY_STOMACH, 1)
	:Register()


Monster.new("killer_beetle")
	:View("killer beetle", 'i', xColor.xBLUE, PersonType.IT, CreatureTemplate.AVG, CreatureClass.INSECT)
	:Basic("1d10+150", "0d0+1000", "1d300+900", CS_VERY_SMALL, "10d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d10 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("acid:1d80 cold:1d80 fire:1d80")
	:Combat("1d10", "2d15")
	:Main("1d1", "6d5", "1d8", "0d0")
	:Description("This beetle scuttles around with great energy, moving half and again as fast as any other beetle you have seen.  Its shell seems thin but the formidable jaws leave no doubt of the damage it can inflict.  Its large antennae make it able to detect creatures around it, visible or not.")
	:Melee(AttackEffectType.POISON, 30)
	:Melee(AttackEffectType.PARALYSE, 70)
	:CorpseEffect(CET_MODIFY_R_PARALYSE, 10)
	:CorpseEffect(CET_MODIFY_STOMACH, 5)
	:Register()


Monster.new("death_beetle")
	:View("death beetle", 'i', xColor.xDARKGRAY, PersonType.IT, CreatureTemplate.HI, CreatureClass.INSECT)
	:Basic("1d30+170", "0d0+1000", "1d300+900", CS_VERY_SMALL, "15d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d15 Dx 1d5 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("acid:1d100 cold:1d100 fire:1d100")
	:Combat("2d10", "3d15")
	:Main("1d1", "6d7", "1d10", "0d0")
	:Description("Extremely heavily armored, the death beetle is a dark blue color bordering on black.  The white markings on it's shell resemble bleached skulls.  Although slow moving, the death beetles venom is extremely potent and unless treated immeadiately can kill an individual within minutes.")
	:Melee(AttackEffectType.POISON, 50)
	:Melee(AttackEffectType.PARALYSE, 100)
	:CorpseEffect(CET_MODIFY_R_PARALYSE, 15)
	:CorpseEffect(CET_MODIFY_STOMACH, 10)
	:Register()


Monster.new("giant_bee")
	:View("giant bee", 'b', xColor.xYELLOW, PersonType.IT, CreatureTemplate.AVG, CreatureClass.INSECT)
	:Basic("1d100+200", "0d0+1000", "1d300+1300", CS_VERY_SMALL, "5d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("1d5", "1d30")
	:Main("5d5", "1d1", "1d2", "0d0")
	:Description("The buzz in the air reminds you more of a hailstorm on a tin roof than an insect but as the giant bee rounds the corner ahead you can see why.  Three feet long and armed with a six inch stinger, this is a far cry from a normal bee.  It doesn't look like it is happy to see you in its territory either.")
	:Melee(AttackEffectType.POISON, 100)
	:Register()

Monster.new("giant_wasp")
	:View("giant wasp", 'b', xColor.xBROWN, PersonType.IT, CreatureTemplate.AVG, CreatureClass.INSECT)
	:Basic("1d100+200", "0d0+1000", "1d300+600", CS_VERY_SMALL, "5d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("1d8", "1d10")
	:Main("7d5", "1d1", "1d2", "0d0")
	:Description("Wasps tend to build nests in areas inaccessible to larger creatures and many wasps can sometimes be found clustered around the opening.  The wasp is stronger than the bee and generally more irritable.  The thin waist of the wasp is a weak point and can be severed with a carefully aimed blow.")
	:Melee(AttackEffectType.POISON, 100)
	:Register()

Monster.new("centipede")
	:View("centipede", 'S', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.INSECT)
	:Basic("1d30+80", "0d0+1000", "1d100+950", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("1d3", "1d3")
	:Main("1d4", "1d1", "1d2", "0d0")
	:Description("Marching forward the centipede comes into view.  Low to the ground and a dark red color, it clearly advertises the fact that it carries poison.  The multiple legs make it easy for the centipede to capture its prey.")
	:Melee(AttackEffectType.PARALYSE, 3)
	:Register()

Monster.new("stegocentipede")
	:View("stegocentipede", 'S', xColor.xDARKGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.INSECT)
	:Basic("1d30+80", "0d0+1000", "1d100+950", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("2d3", "2d3")
	:Main("1d8", "1d2", "1d4", "0d0")
	:Description("Slower than their smaller cousins, the stegocentipede is also that much more heavily armored.  It uses its spiked tail to its advantage to knock prey down before attempting to poison it.")
	:Melee(AttackEffectType.PARALYSE, 7)
	:Register()

Monster.new("dungeon_crawler")
	:View("dungeon crawler", 'c', xColor.xWHITE, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.INSECT)
	:Basic("1d10+50", "0d0+1000", "1d200+300", CS_VERY_SMALL, "10d2")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("2d4", "1d3")
	:Main("1d1", "1d4", "1d2", "0d0")
	:Description("This filthy little insect wanders the floor.  Evolving in the caves, it almost completely forsook the use of eyes, relying on other senses to help it through the darkness.  Usually more of a nuisance than anything else, many adventurers simply crush them with a boot as they walk past.")
	:Melee(AttackEffectType.POISON, 1)
	:Register()

Monster.new("giant_crawler")
	:View("giant crawler", 'c', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.AVG, CreatureClass.INSECT)
	:Basic("1d10+50", "0d0+1000", "1d200+300", CS_SMALL, "10d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("2d4", "1d3")
	:Main("1d1", "1d8", "1d4", "0d0")
	:Description("This appears to be a mound of flesh approximately a foot high.  Only as it moves towards you do you realize that it still lives and sees you as viable prey.  The greyish green surface undulates hypnotically as you watch it ooze its way across the floor.")
	:Melee(AttackEffectType.PARALYSE, 40)
	:Melee(AttackEffectType.POISON, 60)
	:Register()

Monster.new("carrion_crawler")
	:View("carrion crawler", 'c', xColor.xDARKGRAY, PersonType.IT, CreatureTemplate.AVG, CreatureClass.INSECT)
	:Basic("1d10+50", "0d0+1000", "1d100+200", CS_LARGE, "20d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("2d4", "2d15")
	:Main("1d1", "1d10", "1d8", "0d0")
	:Description("This giant bug has numerous paralyzing tentacles just waiting for you to wander into range.  They live mostly in subterranean caverns and feed on dead or dying matter, but they will attack if hungry...")
	:Melee(AttackEffectType.PARALYSE, 100)
	:Melee(AttackEffectType.POISON, 100)
	:Register()
