------------------------------ KOBOLDS --------------------------------------

	Monster.new("kobold")
		:View("kobold", 'k', xColor.xLIGHTGREEN, PersonType.HE, CreatureTemplate.VERY_LOW, CreatureClass.KOBOLD)
		:Basic("1d10+90", "0d0+1000", "0d0+1000", CS_SMALL, "1d200+600")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 1, 0)
		:AI(XStandardAI.CREATURE + XStandardAI.ALLOW_PACK)
		:Stats("St 2d3 Dx 2d3 To 1d3 Le 2d3 Wi 1d3 Ma 1d2 Pe 1d6 Ch 1d3")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "2d3", "2d2")
		:Description("Kobolds resemble nothing better than a small yipping dog that has somehow learned to walk on hind legs and wield weapons.  They are more nuisance than anything else but more than one adventurer has been swarmed under by a pack of them.")
		:LearnSkill(SKT_HEALING, 4)
		:LearnSkill(SKT_FINDWEAKNESS, 4)
		:LearnSkill(SKT_ARCHERY, 4)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 2, 10)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 100)
		:Equip(ItemKind.MISSILEW, ItemType.SHORTBOW, 10)
		:CorpseEffect(CET_DISEASE, 20)
		:Register()

	Monster.new("large_kobold")
		:View("large kobold", 'k', xColor.xGREEN, PersonType.HE, CreatureTemplate.LOW, CreatureClass.KOBOLD)
		:Basic("1d10+90", "0d0+1000", "0d0+1000", CS_SMALL, "1d200+800")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 2, 0)
		:AI(XStandardAI.CREATURE + XStandardAI.ALLOW_PACK)
		:Stats("St 2d5 Dx 2d4 To 2d3 Le 2d4 Wi 1d5 Ma 1d3 Pe 1d8 Ch 1d4")
		:Resist("")
		:Combat("1d3", "1d2")
		:Main("1d3", "1d1", "2d5", "2d3")
		:Description("Somehow this kobold managed to survive its early development. It is not much smarter than the smaller, younger kobolds but definately has more strength.")
		:LearnSkill(SKT_HEALING, 5)
		:LearnSkill(SKT_FINDWEAKNESS, 5)
		:LearnSkill(SKT_ARCHERY, 5)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 3, 12)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 100)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 10)
		:Equip(ItemKind.MISSILEW, ItemType.SHORTBOW, 15)
		:CorpseEffect(CET_DISEASE, 30)
		:Register()

	Monster.new("chieftain_kobold")
		:View("kobold chieftain", 'k', xColor.xGREEN, PersonType.HE, CreatureTemplate.LOW, CreatureClass.KOBOLD)
		:Basic("1d10+90", "0d0+1000", "0d0+1000", CS_SMALL, "1d200+800")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 5, 0)
		:AI(XStandardAI.CREATURE + XStandardAI.ALLOW_PACK)
		:Stats("St 3d5 Dx 2d5 To 3d3 Le 2d4 Wi 1d5 Ma 1d3 Pe 1d8 Ch 1d4")
		:Resist("")
		:Combat("1d4", "1d3")
		:Main("1d4", "1d2", "2d6", "2d3")
		:Description("The largest kobold you have yet seen. There is a glint of wicked intelligence behind its eyes as it approaches.  The kobold chieftain only acheived his position by being stronger, smarter and meaner then everyone else.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:LearnSkill(SKT_ARCHERY, 6)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 4, 15)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 100)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 20)
		:Equip(ItemKind.MISSILEW, ItemType.SHORTBOW, 10)
		:CorpseEffect(CET_DISEASE, 30)
		:Register()


	Monster.new("shaman_kobold")
		:View("kobold shaman", 'k', xColor.xLIGHTCYAN, PersonType.HE, CreatureTemplate.LOW, CreatureClass.KOBOLD)
		:Basic("1d10+90", "0d0+1000", "0d0+1000", CS_SMALL, "1d200+600")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 5, 0)
		:AI(XStandardAI.CREATURE + XStandardAI.ALLOW_PACK)
		:Stats("St 2d4 Dx 2d4 To 2d3 Le 4d4 Wi 4d5 Ma 4d6 Pe 1d6+6 Ch 2d4")
		:Resist("")
		:Combat("1d2", "1d2")
		:Main("1d1", "0d0", "1d8", "5d5")
		:Description("Smeared with arcane symbols in white chalk and wearing a necklace of bones, the kobold shaman is only a little larger than the average kobold.  The intensity of its gaze shows the resentment it feels for having a superior mind locked into an inferior body.  As you watch, it begins a chant to call forth its powers of magic against you...")
		:LearnSpell(SPELL_MAGIC_ARROW)
		:LearnSpell(SPELL_CURE_LIGHT_WOUNDS)
		:LearnSkill(SKT_HEALING, 4)
		:LearnSkill(SKT_CONCENTRATION, 4)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 4, 15)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 100)
		:CorpseEffect(CET_DISEASE, 30)
		:CorpseEffect(CET_MODIFY_MA, 1)
		:Register()


	Monster.new("gnoll")
		:View("gnoll", 'g', xColor.xBROWN, PersonType.HE, CreatureTemplate.ABOVE_LOW, CreatureClass.KOBOLD)
		:Basic("1d10+100", "0d0+1000", "0d0+1000", CS_SMALL, "1d200+800")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 5, 0)
		:AI(XStandardAI.CREATURE + XStandardAI.ALLOW_PACK)
		:Stats("St 3d4 Dx 3d3 To 3d5 Le 1d4 Wi 1d4 Ma 1d4 Pe 2d5 Ch 2d3")
		:Resist("")
		:Combat("1d3", "1d4")
		:Main("1d4", "1d2", "2d5+15", "2d5")
		:Description("A gnoll is to a kobold what a giant is to a man.  This towering cross between man and dog is known for its cunning and strength.  Carrying an axe it will plow right through most opponents leaving them dazed... if they are lucky.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 2, 10)
		:Equip(ItemKind.WEAPON, ItemType.WARAXE, 100)
		:CorpseEffect(CET_MODIFY_TO, 1)
		:Register()

	Monster.new("gnoll_warmaster")
		:View("gnoll warmaster", 'g', xColor.xYELLOW, PersonType.HE, CreatureTemplate.AVG, CreatureClass.KOBOLD)
		:Basic("1d10+100", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+800")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 7, 0)
		:AI(XStandardAI.CREATURE + XStandardAI.ALLOW_PACK)
		:Stats("St 6d4 Dx 7d3 To 6d5 Le 3d4 Wi 3d4 Ma 3d4 Pe 8d5 Ch 2d3")
		:Resist("")
		:Combat("2d5", "2d4")
		:Main("2d5", "3d2", "3d5+25", "2d5")
		:Description("The gnoll warmaster is an eight foot fighting machine.  The double axes it carries weave an intricate dance of death around it as it takes on multiple opponents.  Only a fool would get in this berserker's way.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 3, 10)
		:Equip(ItemKind.WEAPON, ItemType.WARAXE, 100)
		:CorpseEffect(CET_MODIFY_TO, 1)
		:Register()
