------------------------------ UNIQUE --------------------------------------

	Monster.new("elder_gridor")
		:View("Elder Gridor", 'p', xColor.xWHITE, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 0, CreatureTemplate.SUPPRESS_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d3+5 Dx 1d3+5 To 1d3+4 Le 9d5 Wi 1d4+5 Ma 1d4+5 Pe 3d6 Ch 4d4")
		:Resist("")
		:Combat("1d1", "1d1")
		:Main("1d1", "0d0", "1d5+5", "1d5+5")
		:Description("This kind looking old man leans on a cane as he gazes towards you.  As leader of this small farming community, he is responsible for their well being.  He gazes at you and asks for help to a serious problem that has recently arisen and is out of his power to control.")
		:LearnSkill(SKT_HEALING, 6)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 30)
		:Equip(ItemKind.BODY, ItemType.CLOTHES, 100)
		:Equip(ItemKind.WEAPON, ItemType.STAFF, 100)
		:Unique()
		:Register()

	Monster.new("jorgus")
		:View("Jorgus, the master thief", 'p', xColor.xWHITE, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 50, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+30 Dx 1d8+30 To 1d8+15 Le 1d5+15 Wi 1d4+5 Ma 1d4+5 Pe 3d6 Ch 5d5")
		:Resist("")
		:Combat("1d8", "2d2")
		:Main("4d2", "1d3", "1d5+15", "1d5+5")
		:Description("As you enter his dwelling you keep a tight hold on your purse.  The shifty eyes and too quick smile of the owner makes you nervous.  Jorgush is the leader of his outlaw band.  They are known for stealing from the rich and keeping it for themselves.  He appears to evaluate you and the weapons you bear and then gestures to the cahir at the table.  Perhaps he has a proposition for you...")
		:LearnSkill(SKT_STEALING, 15)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 30)
		:Equip(ItemKind.BODY, ItemType.CLOTHES, 100)
		:Unique()
		:Register()

	Monster.new("gekta")
		:View("Gekta, the sheep dog", 'C', xColor.xDARKGRAY, PersonType.NAMED_IT, CreatureTemplate.UNIQUE, CreatureClass.CANINE)
		:Basic("1d10+200", "0d0+1000", "1d100+300", CS_SMALL, "1d200+400")
		:Body("neck", 100, 0)
		:AI(XStandardAI.HI_ANIMAL + XStandardAI.PEACEFUL)
		:Stats("St 1d3+10 Dx 1d5+20 To 1d3+8 Le 1d3+3 Wi 1d3+3 Ma 1d3+3 Pe 5d6 Ch 4d5")
		:Resist("see_invisible:0d0+30")
		:Combat("5d5", "2d6")
		:Main("4d5", "2d1", "1d5+10", "1d1+1")
		:Description("The sheep dog is the mascot for the royal guardians.  It must represent strength, intelligence and unswerving loyalty.  Gekta is the current favorite.  She bounds towards you and knocks you flat, covering you with slobbery dog kisses.")
		:LearnSkill(SKT_HEALING, 15)
		:Unique()
		:Register()

	Monster.new("highpriest")
		:View("Aphilius, the high priest of Avanor", 'p', xColor.xWHITE, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMANOID)
		:Basic("1d10+100", "0d0+800", "0d0+800", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+10 Dx 1d8+15 To 1d8+10 Le 1d5+25 Wi 1d5+25 Ma 1d5+10 Pe 5d6 Ch 6d5")
		:Resist("see_invisible:0d0+100")
		:Combat("1d3", "1d2")
		:Main("1d4", "1d2", "1d5+30", "1d5+10")
		:Description("This compassionate soul gives his time and devotion to maintaining the temple.  He is dressed in the vestments of his position and bears the mitre of the priesthood...")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSkill(SKT_RELIGION, SKILL_MAX_LEVEL)
		:LearnSpell(SPELL_HEAL)
		:Equip(ItemKind.BODY, ItemType.ROBE, 100)
		:Unique()
		:Register()

	Monster.new("ozorik")
		:View("Ozorick, the royal guard captain", 'p', xColor.xLIGHTBLUE, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+30 Dx 1d8+30 To 1d8+15 Le 1d5+15 Wi 1d4+5 Ma 1d4+5 Pe 3d6 Ch 5d5")
		:Resist("see_invisible:0d0+50")
		:Combat("1d8", "2d2")
		:Main("4d2", "1d3", "1d5+15", "1d3+5")
		:Description("Standing just over five feet tall, Ozorick doesn't seem like such an imposing figure but the air of command about him is complete.  His thickly corded neck and arms lightly balance a huge broadsword covered with runes.  He swings it down as you enter and you can't help but gasp as the point cuts right through a stone in the floor and barely even slows.  No one who has seen him wield his mighty sword in battle would dream of opposing him.")
		:LearnSkill(SKT_HEALING, 10)
		:LearnSkill(SKT_FINDWEAKNESS, 10)
		:Unique()
		:Register()

	Monster.new("yohjishiro")
		:View("Yohjishiro, the elven wizard", 'h', xColor.xWHITE, PersonType.NAMED_SHE, CreatureTemplate.UNIQUE, CreatureClass.HUMANOID)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+15 Dx 1d8+40 To 1d8+10 Le 1d5+45 Wi 1d5+45 Ma 1d5+45 Pe 5d6 Ch 7d5")
		:Resist("see_invisible:0d0+100")
		:Combat("1d3", "1d2")
		:Main("1d4", "1d1", "1d5+10", "5d5+50")
		:Description("Last of the elder wizards to live in the vale of Avanor, Yohjishiro quietly tends her herbs and gardens. Her white hair hangs down her back as she kneels down to look at one of her bushes.  Her pointed ears stick out from under a floppy hat that keeps the sun from her eyes.  As she walks through the garden, you notice plants sprouting wherever her feet touch the soil.  Truly she is a power of life.  Frail but intelligent, she remains apart from most of the happenings of Avanor.  Occasionally she will accept a pupil or give aid to those in need.")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSpell(SPELL_LIGHTNING_BOLT)
		:LearnSpell(SPELL_HEAL)
		:Equip(ItemKind.HAT, ItemType.HAT, 100)
		:Equip(ItemKind.WEAPON, ItemType.STAFF, 100)
		:Unique()
		:Register()

	Monster.new("gefeon")
		:View("Gefeon, great master of Fire", 'p', xColor.xRED, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d10+110", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+15 Dx 1d8+40 To 1d8+10 Le 1d5+45 Wi 1d5+45 Ma 1d5+45 Pe 5d6 Ch 7d5")
		:Resist("see_invisible:0d0+100")
		:Combat("1d3", "1d2")
		:Main("1d4", "1d1", "1d5+10", "5d5+50")
		:Description("As master of the eternal flame of Avanor, Gefeon advises the king in all matters arcane.  Clad only in robes and wearing rings of power, he sits and meditates on the state of the universe.  As you watch a furrow creases on his brow as if he is greatly worried by something.")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSpell(SPELL_FIRE_BOLT)
		:LearnSpell(SPELL_HEAL)
		:Unique()
		:Register()

	Monster.new("roderik")
		:View("Roderick, king of Avanor", 'p', xColor.xYELLOW, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d30+150", "0d0+700", "0d0+700", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+55 Dx 1d8+60 To 1d8+40 Le 1d5+35 Wi 1d5+20 Ma 1d5+20 Pe 8d6 Ch 12d5")
		:Resist("see_invisible:0d0+100")
		:Combat("1d6", "1d5")
		:Main("1d8", "1d3", "1d5+70", "1d5+30")
		:Description("The mystical crown of Avanor rests upon the head of this noble looking man.  Curls of red hair stick out from under it but don't detract from his noble bearing.  The sceptre of his rule lies in his hand looking like an ornament but it has been said it is a formidable weapon wrought with great magic in days of yore.  Rodrick's face is happy but you can see great concern in his eyes.  The responsibilty for this nation must truly weigh on him.")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
		:Unique()
		:Register()

	Monster.new("ahkulan")
		:View("Ahk-Ulan, great master of Darkness", 'p', xColor.xDARKGRAY, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Basic("1d30+120", "0d0+900", "0d0+900", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+15 Dx 1d8+40 To 1d8+10 Le 1d5+45 Wi 1d5+45 Ma 1d5+45 Pe 5d6 Ch 7d5")
		:Resist("see_invisible:0d0+100")
		:Combat("1d3", "1d2")
		:Main("1d4", "1d1", "1d5+30", "5d5+50")
		:Description("Once a bright and promising sorcerer, Ahk-Ulan delved into dark magics and soon became the dark and twisted being he is today.  The aura of power and decay surrounds him as he seeks to control the destructive magics he has consumed.")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
		:LearnSkill(SKT_CONCENTRATION, SKILL_MAX_LEVEL)
		:LearnSpell(SPELL_ACID_BOLT)
		:LearnSpell(SPELL_HEAL)
		:Unique()
		:Register()

	Monster.new("todin")
		:View("Todin, dwarven weaponsmith", 'h', xColor.xBROWN, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMANOID)
		:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+30 Dx 1d8+30 To 1d8+15 Le 1d5+15 Wi 1d4+5 Ma 1d4+5 Pe 3d6 Ch 5d5")
		:Resist("see_invisible:0d0+20")
		:Combat("1d8", "2d2")
		:Main("4d2", "1d3", "1d5+15", "1d5+5")
		:Description("Squat, sturdy and built like a boulder here stands the King's twin brother and master smith.  Todin stands at his forge and works the bellows with one hand while nonchalantly shaping a sword with the hammer in his other hand.  The ruddy glow of the forge glimmers on his sweat drenched skin.  Truly he is a master smith as the weapons hanging about the room display his craft.")
		:LearnSkill(SKT_HEALING, 6)
		:LearnSkill(SKT_FINDWEAKNESS, 6)
		:Unique()
		:Register()

	Monster.new("torin")
		:View("Torin the Great, dwarven king", 'h', xColor.xLIGHTGREEN, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMANOID)
		:Basic("1d10+100", "0d0+800", "0d0+800", CS_NORMAL, "1d200+1200")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD + XStandardAI.PEACEFUL)
		:Stats("St 1d8+35 Dx 1d8+20 To 1d8+30 Le 1d5+25 Wi 1d5+25 Ma 1d5+25 Pe 5d6 Ch 4d5")
		:Resist("see_invisible:0d0+100")
		:Combat("1d3", "1d2")
		:Main("1d4", "1d2", "1d5+30", "1d5+10")
		:Description("Twin brother to the master smith, Torin's obvious strength and coloring are all that own the relationship.  The crown on his head glitters and his great golden beard flows over his expansive chest.  The hand he rests on the hammer at his belt belies his prowess in battle.  As your eyes drift to the door at the back of his throne room he clears his throat as if to address you, and draw your attention.")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
		:Unique()
		:Register()

	Monster.new("beelzevile")
		:View("Beelzevile, the horned demon", '&', xColor.xLIGHTCYAN, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.DEMON)
		:Basic("1d30+50", "0d0+1500", "0d0+900", CS_LARGE, "1d400+4000")
		:Body("head body ring ring", 100, CreatureTemplate.SUPPRESS_INVIS + CreatureTemplate.SEE_INVIS)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD)
		:Stats("St 5d5+50 Dx 3d3+10 To 2d15+20 Le 9d5 Wi 3d4 Ma 5d4 Pe 1d3 Ch 1d3")
		:Resist("see_invisible:0d0+70")
		:Combat("0d0+10", "3d15")
		:Main("0d0-10", "0d0+15", "5d5+100", "5d5+100")
		:Description("How he got to the mushroom caves is anyones guess but it is commonly believed that some kobold shaman got a little carried away with his magic and summoned Beelzevile from the netherworld.  Standing 10 feet high and carrying a reek of sulphur about him, he strides around the cavern, furious at being trapped in this cold place.  His massive claws can shred flesh and steel alike.  You catch a glimpse of a magnificent ring on one of his hands as he noisily chews on the haunch of a kobold who wandered a little too close.")
		:Melee(AttackEffectType.POISON, 80)
		:Melee(AttackEffectType.FIRE, 100)
		:Melee(AttackEffectType.COLD, 100)
		:Unique()
		:Register()

	Monster.new("xshee_voo")
		:View("Xshee-Voo, the Cyclope", 'H', xColor.xLIGHTMAGENTA, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.GIANT)
		:Basic("1d30+120", "0d0+900", "0d0+900", CS_LARGE, "1d400+3000")
		:Body("head neck body cloak hand hand boots", 50, 0)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD)
		:Stats("St 5d5+150 Dx 1d10+10 To 1d10+80 Le 1d5+5 Wi 1d5+5 Ma 1d5+5 Pe 1d6 Ch 1d5")
		:Resist("")
		:Combat("1d5", "2d5")
		:Main("0d0-10", "0d0+15", "1d5+70", "1d5+5")
		:Description("Xshee-Voo has lived in his mountain cave for as long as anyone can remember.  He never shows himself outside, and the few that have been in his cave and returned speak of piles of bones and armor slowly decaying.  They also speak of his enormous club which looks to have been carved from the rock of the mountain and is written over with Runes of great power.")
		:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
		:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
		:Unique()
		:Register()


	Monster.new("magnush")
		:View("Magnush, the Kobold Lord", 'k', xColor.xRED, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.KOBOLD)
		:Basic("1d10+120", "0d0+1000", "0d0+1000", CS_SMALL, "1d200+900")
		:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 5, 0)
		:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
		:Stats("St 4d5 Dx 3d5 To 5d3 Le 2d4 Wi 3d5 Ma 3d3 Pe 1d8 Ch 1d4")
		:Resist("")
		:Combat("1d4", "1d3")
		:Main("1d4", "1d2", "2d6", "2d3")
		:Description("Magnush the kobold lord stands before you with all the majesty he can muster.  Bigger than most kobolds (some say his father was a gnoll), he has managed to bully his way to the prime position in his pack.  His mangy fur and crooked legs give him an almost laughable appearance though and you have difficulty hiding your mirth from this overgrown puppy.")
		:LearnSkill(SKT_HEALING, 10)
		:LearnSkill(SKT_FINDWEAKNESS, 10)
		:EquipCount(ItemKind.SCROLL + ItemKind.POTION + ItemKind.BOOK + ItemKind.FOOD, 6, 20)
		:Equip(ItemKind.WEAPON, ItemType.DAGGER, 100)
		:CorpseEffect(CET_DISEASE, 30)
		:LearnSpell(SPELL_CURE_SERIOUS_WOUNDS)
		:Unique()
		:Register()

	Monster.new("rotmoth", "bandit")
		:View("Rotmoth", 'p', xColor.xDARKGRAY, PersonType.NAMED_HE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Description("A wiry, hollow-eyed man with a bandit's cunning and a coward's cruelty, Rotmoth long ago traded whatever honor he once had for easier profits.  He holds his captive in this cave not through any real strength of his own, but because he knows precisely what a frightened hostage is worth in gold - and precisely who to threaten if you come at him with steel drawn instead of coin.")
		:Unique()
		:Register()

	Monster.new("giana", "goodwife")
		:View("Giana", 'p', xColor.xLIGHTRED, PersonType.NAMED_SHE, CreatureTemplate.UNIQUE, CreatureClass.HUMAN)
		:Description("Giana's dress is torn at the hem and her eyes dart toward the cave entrance at every sound, but there's a stubborn set to her jaw that captivity hasn't managed to break.  Snatched from the valley for ransom, she has spent her time here watching for any chance at rescue - and once freed, she intends to walk every step of the way home herself.")
		:Unique()
		:Register()
