------------------------------ OOZE, JELLY, etc. --------------------------------------

Monster.new("gray_ooze")
	:View("gray ooze", 'j', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.BLOB)
	:Basic("1d10+40", "0d0+1000", "1d100+600", CreatureSize.VERY_SMALL, "1d10+10")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("acid:0d0+100 poison:0d0+100")
	:Combat("3d5", "1d3")
	:Main("1d2", "0d0", "1d3", "0d0")
	:Description("This quivering gelatinous mass slowly oozes across the floor towards you.  It appears almost that two separate intelligences control the creature, straining to separate from each other.  It is said that the gray ooze steals life energy from those it attacks in order to reproduce.  It also is rumored to have a deadly poison.")
	:Melee(AttackEffectType.POISON, 15)
	:CorpseEffect(CET_MODIFY_R_POISON, 1)
	:CorpseEffect(CET_POISON, 10)
	:Register()

Monster.new("gelatinous_cube")
	:View("gelatinous cube", 'j', xColor.xWHITE, PersonType.IT, CreatureTemplate.AVG, CreatureClass.BLOB)
	:Basic("1d10+50", "0d0+1000", "1d100+200", CreatureSize.LARGE, "20d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d1 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d1 Ch 1d1")
	:Resist("")
	:Combat("2d4", "2d15")
	:Main("1d1", "1d10", "1d8", "0d0")
	:Description("As you watch this clear mass you realize that you can still see the remains of its last meal suspended inside.  The skull seems to laugh at you as ready your weapon to face this three foot oozing mass.  The skelatal hand still grips the remains of a sword, slowly being digested.")
	:Melee(AttackEffectType.PARALYSE, 100)
	:Melee(AttackEffectType.ACID, 100)
	:Register()
