------------------------------ ORCS --------------------------------------

Monster.new("orc")
	:View("orc", 'o', xColor.xLIGHTGREEN, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+15 Dx 1d5+5 To 2d5+15 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("Orcs are roughly dwarf sized with a light green pallor to their skin.  Not extremely intelligent, they avoid sunlight whenever possible.  It has been speculated that they were once humans elves or dwarves but something drove them deep underground and they became the hardy race they are today.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:Register()

Monster.new("large_orc")
	:View("large orc", 'o', xColor.xGREEN, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+20 Dx 1d5+5 To 2d5+20 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("Bigger, meaner and nastier than its smaller cousins, this orc stands near as tall as a man.  It bears a cruel looking axe and is well armored.  The wicked grin on its face tells you that it will enjoy picking your flesh from your bones.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:CorpseEffect(CET_MODIFY_ST, 1)
	:Register()

Monster.new("hill_orc")
	:View("hill orc", 'o', xColor.xYELLOW, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+25 Dx 1d5+5 To 2d5+25 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("Hill orcs are descendants of orcs that left their caves to live back under the sky.  They still prefer to sleep during the day but move around enough during the day to acquire a healthy tan.  Perhaps their return to sunlight is the reason they are stronger than their cousins.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:CorpseEffect(CET_MODIFY_ST, 1)
	:Register()

Monster.new("dark_orc")
	:View("dark orc", 'o', xColor.xDARKGRAY, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+30 Dx 1d5+5 To 2d5+30 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("Dark orcs retreated to the farthest corners of the caverns and were enslaved by the other orcs.  They were used to delve great cities beneath the earth like the dwarves.  Because of all this manual labor they grew extremely strong.  Before any battle, they cover themselves in coal dust to appear jet black and frighten their opponents.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:CorpseEffect(CET_MODIFY_ST, 1)
	:Register()

Monster.new("lieutenant_orc")
	:View("orc lieutenant", 'o', xColor.xBROWN, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+30 Dx 1d5+5 To 2d5+30 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("\"Git yur sorry corpses movin'!\"  Orc sergeants act as the first tier of leadership for any orcish raid.  Known to be exceptionally mean spirited, they have been seen to kill their own troops in order to \"inspire\" the rest to better results.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:CorpseEffect(CET_MODIFY_ST, 2)
	:Register()

Monster.new("captain_orc")
	:View("orc captain", 'o', xColor.xBROWN, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+40 Dx 1d5+5 To 2d5+40 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("Captain is a precarious position for any orc.  Displeased chiefs might have their captains killed for any failure, success or even on a whim.  The orcs under him are ready to mutiny and kill him for his position.  Thus the orc captain is always on edge and ready to strike down anything that might pose a danger.  His large frame and hefty axe are usually more than adequate to take care of any and all threats.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:CorpseEffect(CET_MODIFY_ST, 2)
	:Register()

Monster.new("chieftain_orc")
	:View("orc chieftain", 'o', xColor.xBLUE, PersonType.HE, CreatureTemplate.AVG, CreatureClass.ORC)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CreatureSize.NORMAL, "1d400+1400")
	:Body("head neck body cloak hand hand ring ring gloves boots light_source tool missile_weapon missile", 30, 0)
	:AI(XStandardAI.CREATURE)
	:Stats("St 2d5+50 Dx 1d5+5 To 2d5+50 Le 1d4 Wi 1d4 Ma 1d4 Pe 3d3 Ch 1d5")
	:Resist("")
	:Combat("1d6", "2d4")
	:Main("2d3", "1d2", "2d5+25", "2d5")
	:Description("The orc chieftain is the biggest, meanest orc you have ever seen.  His skin alone looks tougher than studded leather.  The axe he carries is well worn and scarred from many battles.  Only someone this mean and nasty could get the various orc tribes to work together for a raid.")
	:LearnSkill(SKT_HEALING, 6)
	:LearnSkill(SKT_FINDWEAKNESS, 6)
	:EquipCount(ItemKind.SCROLL + ItemKind.POTION, 3, 50)
	:Equip(ItemKind.WEAPON, ItemType.BATTLEAXE, 100)
	:CorpseEffect(CET_MODIFY_ST, 3)
	:Register()
