------------------------------ RATS --------------------------------------

Monster.new("rat")
	:View("rat", 'r', xColor.xBROWN, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.RAT)
	:Basic("1d30+90", "0d0+1000", "1d200+600", CS_VERY_SMALL, "5d4")
	:Body("", 0, 0)
	:AI(XStandardAI.COWARD + XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PACK)
	:Stats("St 1d2 Dx 2d4 To 1d2 Le 1d1 Wi 1d1 Ma 1d1 Pe 2d4 Ch 1d1")
	:Resist("fire:5d5-50 cold:2d10")
	:Combat("0d0", "1d2")
	:Main("1d3", "0d0", "1d3", "0d0")
	:Description("Scuttling about in the shadows, rats can be found most places in the valley.  Those in the caves have grown larger and bolder and present a threat to any explorers.")
	:CorpseEffect(CET_VOMIT, 0)
	:Register()

Monster.new("large_rat", "rat")
	:View("large rat", 'r', xColor.xBROWN, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.RAT)
	:Basic("1d30+90", "0d0+1000", "1d200+600", CS_VERY_SMALL, "10d4")
	:Stats("St 1d3 Dx 2d5 To 1d3")
	:Resist("fire:5d5-25 cold:3d10")
	:Combat("1d2", "1d3")
	:Main("2d2", "1d1", "2d3", "0d0")
	:Description("These large rodents have grown almost to the size of a housecat.  Their sharp incisors glitter brightly in the light from your torch.  It is said that their teeth never stop growing and they must constantly chew in order to keep them trimmed.  This particular rat seems to think your arm would make a great chew stick.")
	:Register()

Monster.new("black_rat", "rat")
	:View("black rat", 'r', xColor.xDARKGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.RAT)
	:Basic("1d30+100", "0d0+1000", "1d200+500", CS_VERY_SMALL, "10d4")
	:Stats("St 1d5 Dx 2d8 To 2d2 Pe 2d5")
	:Resist("fire:5d5 cold:5d10 acid:5d10+40")
	:Combat("1d4", "1d6")
	:Main("2d3", "1d2", "3d3", "0d0")
	:Description("A foot long and covered in jet black fur, this rat appears rather harmless (as far as rats go).  Then you notice the wildness in its eyes and slight froth dripping from its jaw.  Surely this is the type of rat blamed for the spread of many diseases.  Suddenly you become much more wary about letting it nip at you, even a scratch could cause the dreaded black plague.")
	:Melee(AttackEffectType.DISEASE, 30)
	:CorpseEffect(CET_VOMIT, 0)
	:Register()

Monster.new("huge_rat", "rat")
	:View("huge rat", 'r', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.RAT)
	:Basic("1d30+110", "0d0+1000", "1d200+400", CS_SMALL, "50d4")
	:Stats("St 2d5 Dx 2d7 To 3d2 Pe 2d6")
	:Resist("cold:5d10")
	:Combat("2d4", "2d3")
	:Main("2d3", "2d2", "5d3", "0d0")
	:Description("Come closer my child and you will hear of the giant rats that come to take bad children away...  Deep in the caves of Avanor they nest, big as a wolf and meaner too.  They come at night to take bad little children and feed them to their young.  Oh!  I see it is bedtime, you better hurry and get in bad or they might think you are one of the bad ones...")
	:Melee(AttackEffectType.DISEASE, 30)
	:Melee(AttackEffectType.POISON, 20)
	:CorpseEffect(CET_VOMIT, 0)
	:Register()
