------------------------------ REPTILE --------------------------------------

Monster.new("small_snake")
	:View("small snake", 'R', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.REPTILE)
	:Basic("1d10+80", "0d0+1000", "1d200+900", CS_VERY_SMALL, "3d4")
	:Body("", 0, 0)
	:AI(XStandardAI.INSECT)
	:Stats("St 1d1 Dx 1d2 To 1d1 Le 1d1 Wi 1d1 Ma 1d1 Pe 1d2 Ch 1d1")
	:Resist("cold:1d10-90")
	:Combat("2d5", "1d3")
	:Main("1d3", "0d0", "1d2", "0d0")
	:Description("This tiny creature lies in the dust looking like a piece of rope.  Suddenly a pink tongue protrudes from one end and eyes open sensing your presence.  Though unimposing at best, this snake harbors one of the deadliest poisons in the valley.")
	:Register()

Monster.new("gray_snake", "small_snake")
	:View("gray snake", 'R', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.REPTILE)
	:Basic("1d10+80", "0d0+1000", "1d200+900", CS_VERY_SMALL, "5d4")
	:Stats("St 1d2 Dx 1d4 To 1d2 Pe 1d2")
	:Resist("cold:1d10-50")
	:Combat("2d5", "1d3")
	:Main("1d3", "0d0", "1d3", "0d0")
	:Description("A long serpent slithers towards you, its grey-black scales making it hard to see against the stone of the cavern floor.  The pale green eyes glimmer with hunger.  Its pink tounge tastes the air as it contemplates this, its lastest meal... YOU!")
	:Register()

Monster.new("brown_snake", "gray_snake")
	:View("brown snake", 'R', xColor.xBROWN, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.REPTILE)
	:Resist("cold:1d10-30")
	:Combat("2d5", "1d4")
	:Main("1d3", "0d0", "1d5", "0d0")
	:Description("This snake will normally keep to the forests and caves of Avanor.  The naturally mottled brown coat allows it to blend in with the area around it.  Though not a great danger, travelers are urged to leave them alone since others may be nearby.")
	:Register()

Monster.new("salamander", "gray_snake")
	:View("salamander", 'R', xColor.xRED, PersonType.IT, CreatureTemplate.LOW, CreatureClass.REPTILE)
	:Resist("cold:1d10-50 fire:1d90")
	:Combat("2d4", "1d4")
	:Main("1d9", "1d3", "1d3", "0d0")
	:Description("Salamanders prefer living in dark, damp caves and eating the bugs that fly around.  The release of Power mutated the salamanders in the valley of Avanor until they were 4 feet long and had a taste for warm blooded flesh.  They can't see well but they have a powerful bite.")
	:Melee(AttackEffectType.FIRE, 100)
	:CorpseEffect(CET_MODIFY_R_FIRE, 1)
	:Register()

Monster.new("large_snake", "gray_snake")
	:View("large snake", 'R', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.REPTILE)
	:Basic("1d10+80", "0d0+1000", "1d200+800", CS_VERY_SMALL, "10d4")
	:Stats("St 1d3 Dx 1d5 To 1d3 Pe 1d2")
	:Resist("cold:1d10-40")
	:Combat("6d5", "1d5")
	:Main("1d4", "1d1", "2d3", "0d0")
	:Description("This serpent seems to have been lost from some sort of travelling show.  Its emerald green scales show up clearly against the stone and dirt.  Idly you wonder how it has survived for so long seeing as travelling shows just don't reach the valley anymore.  Then you realize that the snake is already closing the distance between its position and yours and suddenly you know exactly how it survived.")
	:Melee(AttackEffectType.POISON, 10)
	:CorpseEffect(CET_MODIFY_R_POISON, 1)
	:Register()

Monster.new("cobra", "gray_snake")
	:View("cobra", 'R', xColor.xGREEN, PersonType.IT, CreatureTemplate.LOW, CreatureClass.REPTILE)
	:Basic("1d10+90", "0d0+1000", "1d200+700", CS_VERY_SMALL, "15d4")
	:Stats("St 1d3 Dx 1d7 To 2d2 Pe 1d4")
	:Resist("cold:1d10-30")
	:Combat("7d5", "1d7")
	:Main("1d8", "1d1", "3d3", "0d0")
	:Description("The cobra looks much like a normal snake until it lifts its head and spreads its hood.  Then the markings clearly indicate the danger you face.  A cobra's poison is more deadly than other snakes and the cobra is much more aggressive.")
	:Melee(AttackEffectType.POISON, 40)
	:CorpseEffect(CET_MODIFY_R_POISON, 2)
	:Register()

Monster.new("king_cobra", "gray_snake")
	:View("king cobra", 'R', xColor.xLIGHTRED, PersonType.IT, CreatureTemplate.AVG, CreatureClass.REPTILE)
	:Basic("1d10+90", "0d0+1000", "1d200+500", CS_VERY_SMALL, "20d4")
	:Stats("St 1d7 Dx 1d8 To 3d2 Pe 2d3")
	:Resist("cold:1d10-20")
	:Combat("8d5", "1d12")
	:Main("2d5", "2d2", "4d3", "0d0")
	:Description("The distinct crown shaped mark on the back of this snake's head gave the title it now carries.  However, if you are close enough to see the crown than you should have been able to distinguish it by its size alone.  Bigger, faster and stronger than its smaller cousin, the king cobra is best left alone by anyone without several anti-venom potions.")
	:Melee(AttackEffectType.POISON, 60)
	:CorpseEffect(CET_MODIFY_R_POISON, 5)
	:Register()

Monster.new("rattlesnake", "gray_snake")
	:View("rattlesnake", 'R', xColor.xRED, PersonType.IT, CreatureTemplate.AVG, CreatureClass.REPTILE)
	:Basic("1d10+90", "0d0+1000", "1d200+500", CS_VERY_SMALL, "10d4")
	:Stats("St 2d4 Dx 2d5 To 3d2 Pe 2d3")
	:Resist("cold:1d10-30")
	:Combat("10d5", "1d12")
	:Main("1d5", "1d2", "5d3", "0d0")
	:Description("An ominous rattle sounds from ahead of you as a coiled rattlesnake prepares to defend its territory.  Poison drips from its fangs and the cold glint in its eyes seem to foreshadow your certain death if you don't retreat now.  It may even be too late...")
	:Melee(AttackEffectType.POISON, 80)
	:CorpseEffect(CET_MODIFY_R_POISON, 10)
	:Register()
