------------------------------ UNDEAD --------------------------------------

Monster.new("skeleton")
	:View("skeleton", 's', xColor.xWHITE, PersonType.IT, CreatureTemplate.VERY_LOW, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("head neck body hand hand", 2, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
	:Stats("St 4d3 Dx 2d2 To 2d3 Le 1d3 Wi 1d3 Ma 1d2 Pe 1d2 Ch 1d1")
	:Resist("")
	:Combat("1d3", "2d3")
	:Main("1d3", "1d2", "1d8", "1d3")
	:Description("Returned to life by evil magics, this creature shuffles towards you, fueled by hate for those still living.  It seeks only to return to the sweet oblivion of death, but first it wants to take you with it.")
	:Register()

Monster.new("zombie")
	:View("zombie", 'z', xColor.xBROWN, PersonType.IT, CreatureTemplate.LOW, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("head neck body hand hand boots", 5, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
	:Stats("St 8d3 Dx 2d2 To 5d5 Le 1d3 Wi 1d3 Ma 1d2 Pe 1d2 Ch 1d1")
	:Resist("")
	:Combat("1d3", "2d3")
	:Main("1d3", "1d2", "2d9", "1d3")
	:Description("The zombie stumbles across the floor, leaving a trail of decaying flesh behind it.  Though muscles makes the zombie stronger, the magics that animate it can do nothing to preserve the diseased hulk.  The stench is almost unbearable.")
	:Melee(AttackEffectType.PARALYSE, 2)
	:Register()

Monster.new("ghoul")
	:View("ghoul", 'z', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.LOW, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("head neck body hand hand boots", 10, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
	:Stats("St 10d3 Dx 2d3 To 7d5 Le 1d3 Wi 1d3 Ma 1d2 Pe 1d2 Ch 1d1")
	:Resist("")
	:Combat("1d3", "2d3")
	:Main("1d2", "1d4", "3d9", "1d3")
	:Description("The pasty white flesh of the ghoul is the result of numerous alchemical and magical experiments.  The preserved flesh makes it strong and tough but not much else.  Ghouls are not smart and have been observed attacking walls that stand in their way.")
	:Melee(AttackEffectType.PARALYSE, 10)
	:Register()

Monster.new("ghost")
	:View("ghost", 'G', xColor.xLIGHTGRAY, PersonType.IT, CreatureTemplate.ABOVE_LOW, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("", 0, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
	:Stats("St 6d5 Dx 4d5 To 2d5 Le 5d5 Wi 5d5 Ma 5d5 Pe 1d2 Ch 1d1")
	:Resist("invisible:2d5 see_invisible:2d5+10")
	:Combat("4d4", "2d4")
	:Main("6d4", "0d0", "1d9", "1d3")
	:Description("A chill breeze passing by is all most ever felt of this spirit set to wander upon the earth.  Those with good eyesight may spot ghosts in the dark corridors of the earth, but they do not take kindly to people who invade their domain.")
	:Register()

Monster.new("spectre")
	:View("spectre", 'G', xColor.xMAGENTA, PersonType.IT, CreatureTemplate.AVG, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("", 0, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
	:Stats("St 6d5 Dx 4d5 To 2d5 Le 5d5 Wi 5d5 Ma 5d5 Pe 1d2 Ch 1d1")
	:Resist("invisible:2d5+5 see_invisible:2d5+15")
	:Combat("4d4", "4d4")
	:Main("6d4", "0d0", "2d9", "1d3")
	:Description("It is said the spectres were once the evil people of this earth.  Forbidden entry into the next world, their spirits seek to destroy those of this world.  They are almost never seen before their chill hands take hold upon the heart of their victim.")
	:LearnSpell(SPELL_DRAIN_LIFE)
	:LearnSkill(SKT_CONCENTRATION, 10)
	:Register()

Monster.new("dread")
	:View("dread", 'G', xColor.xBROWN, PersonType.IT, CreatureTemplate.HI, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("", 0, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM)
	:Stats("St 6d10 Dx 5d5 To 3d5 Le 8d5 Wi 8d5 Ma 8d5 Pe 1d2 Ch 1d1")
	:Resist("invisible:2d5+10 see_invisible:2d5+20")
	:Combat("6d6", "5d5")
	:Main("8d5", "0d0", "8d5", "10d8")
	:Description("Panic and fear threaten to overwhelm you as you face thise evil spirit.  Aptly named for the feelings it causes, The dread seeks only to destroy all living things.  So stealthy and invisible are they that most people will never know exactly what did them in.")
	:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
	:LearnSkill(SKT_CONCENTRATION, 10)
	:LearnSpell(SPELL_DRAIN_LIFE)
	:Register()

Monster.new("vampire")
	:View("vampire", 'V', xColor.xBLUE, PersonType.HE, CreatureTemplate.HI, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("head neck body cloak hand hand ring ring gloves boots", 100, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD)
	:Stats("St 4d6 Dx 5d5 To 3d5 Le 8d5 Wi 8d5 Ma 8d8 Pe 1d2 Ch 1d1")
	:Resist("invisible:2d5+30 see_invisible:2d5+30")
	:Combat("4d6", "3d5")
	:Main("8d5", "0d0", "3d5", "10d10")
	:Description("This foul creature of the night drinks of its victims for sustenance, slowly draining their victim of life until they also become a vampire.  They possess numerous abilities, and have much power in the undead realms.  They fear light and holy powers, but are immune to many non-magical weapons.")
	:Melee(AttackEffectType.PARALYSE, 20)
	:LearnSkill(SKT_BACKSTABBING, SKILL_MAX_LEVEL)
	:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
	:LearnSkill(SKT_CONCENTRATION, SKILL_MAX_LEVEL)
	:LearnSpell(SPELL_DRAIN_LIFE)
	:Register()

Monster.new("lich")
	:View("lich", 'L', xColor.xLIGHTGRAY, PersonType.HE, CreatureTemplate.HI, CreatureClass.UNDEAD)
	:Basic("1d10+95", "0d0+1000", "0d0+1000", CS_NORMAL, "1d200+1200")
	:Body("head neck body cloak hand hand ring ring gloves boots", 100, 0)
	:AI(XStandardAI.RANDOM_MOVE + XStandardAI.ALLOW_PICK_UP + XStandardAI.ALLOW_WEAR_ITEM + XStandardAI.COWARD)
	:Stats("St 3d8 Dx 5d5 To 3d5 Le 8d5 Wi 10d5 Ma 10d8 Pe 1d2 Ch 1d1")
	:Resist("invisible:2d5+30 see_invisible:2d5+40")
	:Combat("2d5", "1d4")
	:Main("8d5", "0d0", "3d5", "10d10")
	:Description("\"Once a sorcerer, always a sorcerer.\" Liches were powerful magic wielders in life and they continue to wield that power after their death.  They are able to summon great magics down upon the living and absorb living energies to sustain their own existence.")
	:LearnSkill(SKT_HEALING, SKILL_MAX_LEVEL)
	:LearnSkill(SKT_FINDWEAKNESS, SKILL_MAX_LEVEL)
	:LearnSkill(SKT_CONCENTRATION, SKILL_MAX_LEVEL)
	:LearnSpell(SPELL_DRAIN_LIFE)
	:LearnSpell(SPELL_MAGIC_ARROW)
	:LearnSpell(SPELL_HEAL)
	:Register()
